# -*- coding: utf-8 -*-
"""Per-locale strings for the NotiKeep landing page.

Each locale has the same set of keys. Build script substitutes them
into _template.html.
"""

STRINGS = {

# =============================================================
# en (English) — canonical
# =============================================================
"en": {
    "F10_T": "Conversation view",
    "F10_P": "Messaging apps appear as chat threads — grouped by sender, with photos shown inline.",
    "PV_HEADING": "See it in action",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": "NotiKeep — Notification History Log",
    "META_DESCRIPTION": "Save your notifications, photos included. Open YouTube notifications in any browser. 7-day free trial of all features. Ad-free, all data stays on-device.",
    "OG_TITLE": "NotiKeep — Notification History Log",
    "OG_DESCRIPTION": "Save your notifications, photos included. Open YouTube notifications in any browser. 7-day free trial. Ad-free, all data on-device.",
    "HERO_H1_HTML": 'Save with <span class="accent">NotiKeep</span>',
    "HERO_TAGLINE": "Photos, codes, messages — kept as long as you want.",
    "HERO_IMG_ALT": "NotiKeep main screen — notifications from WhatsApp, Instagram, YouTube, Gmail, and more",
    "CTA_GET": "Get NotiKeep on Google Play",
    "TRIAL_NOTE": "",
    "H2_PAIN": "Sound familiar?",
    "PAIN_1": "That WhatsApp photo a friend just sent — gone the moment you swiped",
    "PAIN_2": "",
    "PAIN_3": '"Uploading…" "App is running in the background" — your tray full of pings you didn\'t want to see',
    "PAIN_4": "That DM you skimmed half-asleep — now nowhere to be found",
    "PAIN_OUTRO": "NotiKeep keeps them for you.",
    "H2_HOW": "How it works",
    "STEP1_TITLE": "Install &amp; grant Notification Access",
    "STEP1_BODY": "First, allow notification access. The app needs it to read incoming notifications.",
    "STEP2_TITLE": "Use your phone normally",
    "STEP2_IMG_ALT": "NotiKeep main archive view with per-app bell control",
    "STEP2_BODY": "NotiKeep runs in the background. Disabling battery optimization for it is recommended.",
    "STEP3_TITLE": "Search by keyword",
    "STEP3_IMG_ALT": "Swiping a notification to archive it in NotiKeep",
    "STEP3_BODY": "Full-text search to find any notification. Bookmark the important ones for quick access later.",
    "H2_TWO_FEATURES": "Two features that set NotiKeep apart",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Image Timeline",
    "IMT_LEAD": 'Browse photos that arrived in notifications — YouTube thumbnails from channels you follow, Google Photos "on this day" memories, photos sent on WhatsApp, news thumbnails, Instagram posts. If a notification carries a photo, it\'s saved.',
    "IMT_ARIA": "Phone tilted to the side with photo cards flying out from the Image Timeline screen",
    "IMT_CAPTION_HTML": 'Tap a YouTube thumbnail to play it directly in the browser of your choice (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">Pro feature: below</a>).',
    "YT_TITLE": "YouTube notifications, your browser",
    "YT_LEAD": "Tap a saved YouTube notification to play it in Chrome, Firefox, Brave, or any other browser of your choice (Pro only).",
    "YT_IMG_ALT": "YouTube notification with browser-chooser dialog showing Chrome, Firefox, Brave",
    "YT_CAPTION": "",
    "H2_WHAT_YOU_GET": "What you get",
    "F1_T": "Image Timeline",
    "F1_P": "Browse every photo that came through a notification, grouped by date.",
    "F2_T": "YouTube in any browser",
    "F2_P": "Open YouTube notifications in the browser of your choice.",
    "F3_T": "Smart noise filter",
    "F3_P": "Progress bars, foreground services, system pings — automatically dropped.",
    "F4_T": "Bookmarks",
    "F4_P": "Star important ones. No expiry, even on Free.",
    "F5_T": "Backup with images",
    "F5_P": "Archive plus images in one ZIP. Survives device migration.",
    "F6_T": "Custom themes",
    "F6_P": "Customize the app's color palette.",
    "F7_T": "Per-app bell control",
    "F7_P": "Save notifications silently.",
    "F8_T": "Full-text search",
    "F8_P": "Find any notification by content. Free: 30 days, Pro: forever.",
    "F9_T": "12 languages",
    "F9_P": "English, 日本語, 한국어, 中文, Español, Français, Deutsch and more.",
    "H2_PRICING": "Pricing",
    "BEST_VALUE_LABEL": "Best value",
    "PRICE_MONTHLY": "Monthly",
    "PER_MO": "/mo",
    "PRICE_NOTE_MONTHLY": "Cancel anytime",
    "PRICE_YEARLY": "Yearly",
    "PER_YR": "/yr",
    "PRICE_NOTE_YEARLY": "~16% off the monthly rate",
    "PRICE_LIFETIME": "Lifetime",
    "PRICE_NOTE_LIFETIME": "One-time, no subscription",
    "PRICING_DISCLAIMER": "Prices shown are in USD. Google Play displays the equivalent in your local currency at checkout.",
    "TRIAL_BANNER_HTML": "7-day free trial to start. No charge when the trial ends.",
    "H3_FREE_VS_PRO": "Free vs Pro",
    "TBL_FEATURE": "Feature",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "Notification archive",
    "TBL_R2": "Image preservation (in detail view)",
    "TBL_R3": "Smart noise filter",
    "TBL_R4_LABEL": "Retention",
    "TBL_R4_FREE": "30 days (fixed)",
    "TBL_R4_PRO": "Configurable · 30 days → unlimited",
    "TBL_R5_LABEL": "Search",
    "TBL_R5_FREE": "Last 30 days",
    "TBL_R5_PRO": "Entire archive",
    "TBL_R6_LABEL": "Bookmarks · Mute · App block",
    "TBL_R6_FREE": "5 each",
    "TBL_R6_PRO": "Unlimited",
    "TBL_R7": "Image Timeline (browsable image grid)",
    "TBL_R8": "Open YouTube in any browser",
    "TBL_R9": "Backup with images",
    "TBL_R10_LABEL": "Custom themes",
    "TBL_R10_PRO": "3 slots",
    "CTA_TRY_FREE": "Try free for 7 days",
    "H2_FIT": "Is NotiKeep for you?",
    "FIT_GREAT_TITLE": "Great fit if you…",
    "FIT_GREAT_1": "Have ever swiped away a notification you needed and instantly regretted it",
    "FIT_GREAT_2": "Want to keep the photos friends send via messaging apps",
    "FIT_GREAT_3": "Need offline records of WhatsApp, Messenger, SMS, or Gmail notifications",
    "FIT_GREAT_4": "Are tired of the YouTube app pulling you into Shorts every time you tap a notification",
    "FIT_GREAT_5": "Care about keeping your data on-device, not on someone's cloud",
    "FIT_SKIP_TITLE": "Skip if you…",
    "FIT_SKIP_1": "Are happy with Android's built-in 24-hour notification history",
    "FIT_SKIP_2": "",
    "FIT_SKIP_3": "",
    "FIT_SKIP_4": "",
    "H2_FAQ": "FAQ",
    "FAQ1_Q": "Can NotiKeep see notifications I received before I installed it?",
    "FAQ1_A": "<strong>No.</strong> NotiKeep only saves notifications that arrive after it's installed and Notification Access is granted.",
    "FAQ2_Q": "Which Android versions are supported?",
    "FAQ2_A": "Android 9.0 and newer.",
    "FAQ3_Q": "How much storage does NotiKeep use?",
    "FAQ3_A": "Text notifications are tiny — a few MB covers months. Storage is mostly images: each saved photo is around 20–80 KB. A heavy user with 1,000 image-bearing notifications a month uses ~30–80 MB. If you're concerned, shorten the retention period.",
    "FAQ4_Q": "What happens to my data if I uninstall?",
    "FAQ4_A": "All NotiKeep data — notifications, images, preferences, bookmarks — is stored on-device, so uninstalling deletes it. To keep it across a reinstall or new phone, consider Backup &amp; Restore (Pro feature) first.",
    "FAQ5_Q": "What permissions does NotiKeep need?",
    "FAQ5_A": "Just notification access. No location, no contacts, no other access.",
    "FAQ6_Q": "",
    "FAQ6_A": "",
    "FAQ7_Q": "Can I export my data?",
    "FAQ7_A": "Pro creates a ZIP with the database, saved images, bookmarks, mute lists, and settings — all in one. Restore on a new phone in one step. The save location is up to you.",
    "FAQ8_Q": "What happens at the end of the 7-day trial?",
    "FAQ8_A": "You revert to Free. No auto-renewal. If you want Pro, pick a plan from the upgrade screen.",
    "FAQ9_Q": "Will it drain my battery or slow my phone?",
    "FAQ9_A": "NotiKeep only does work when a notification arrives. It doesn't sit there draining your battery.",
    "FAQ10_Q": "Where is my data stored?",
    "FAQ10_A": "All data stays on-device. Backups go only to a path you choose.",
    "H2_RECENT": "Recent updates",
    "CL_127": "",
    "CL_126": "",
    "CL_125": "",
    "CL_124": "",
    "CL_123": "",
    "EARLIER_LABEL": "",
    "EARLY_1": "",
    "EARLY_2": "",
    "EARLY_3": "",
    "EARLY_4": "",
    "EARLY_5": "",
    "FINAL_CTA_H2": "Notifications, with NotiKeep",
    "FINAL_CTA_P": "Try free for 7 days.",
    "FOOTER_MADE_BY": 'NotiKeep is made by <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a>',
    "FOOTER_PLAY": "App on Google Play",
    "FOOTER_PRIVACY": "Privacy Policy",
    "FOOTER_SUPPORT": "Support",
    "FOOTER_DISCLOSURE": "",
},

# =============================================================
# ja (Japanese)
# =============================================================
"ja": {
    "F10_T": "会話ビュー",
    "F10_P": "メッセージアプリを送信者別のチャット表示で。写真も会話の中にそのまま。",
    "PV_HEADING": "動きを見る",
    "PV_VIDEO_ID": "NM1_dw0tZqg",
    "TITLE": "NotiKeep — 通知履歴",
    "META_DESCRIPTION": "写真を含む通知を保存します。YouTubeの通知は好きなブラウザで開けます。7日間は無料ですべての機能をお使いいただけます。広告なし、データは端末内にのみ保存されます。",
    "OG_TITLE": "NotiKeep — 通知履歴",
    "OG_DESCRIPTION": "写真を含む通知を保存。YouTubeの通知は好きなブラウザで開けます。7日間無料、広告なし、データは端末内にのみ保存。",
    "HERO_H1_HTML": 'NotiKeepで <span class="accent">記録する</span>',
    "HERO_TAGLINE": "写真もコードもメッセージもいつまでも残せる。",
    "HERO_IMG_ALT": "NotiKeepのメイン画面 — WhatsApp、Instagram、YouTube、Gmailなどの通知一覧",
    "CTA_GET": "Google Playで手に入れる",
    "TRIAL_NOTE": "",
    "H2_PAIN": "こんなことありませんか？",
    "PAIN_1": "LINEで友達が送ってきた写真がスワイプした瞬間に消えた",
    "PAIN_2": "",
    "PAIN_3": "「アップロード中…」「バックグラウンドで実行中」、通知バーが埋まる",
    "PAIN_4": "半分寝ながら流し見したDMが見つからない",
    "PAIN_OUTRO": "NotiKeepには通知が残ってる。",
    "H2_HOW": "使い方",
    "STEP1_TITLE": "インストールして通知アクセスを許可",
    "STEP1_BODY": "まず、通知へのアクセス許可をします。アプリが通知を読み取るために必要です。",
    "STEP2_TITLE": "あとは普通にスマホを使うだけ",
    "STEP2_IMG_ALT": "NotiKeepのメイン画面、アプリごとのベル制御",
    "STEP2_BODY": "NotiKeepはバックグラウンドで動きます。バッテリーの最適化はオフにすることを推奨します。",
    "STEP3_TITLE": "キーワードで検索",
    "STEP3_IMG_ALT": "NotiKeepで通知をスワイプしてアーカイブ",
    "STEP3_BODY": "全文検索して大事な通知を探せます。大事なものはブックマーク、すぐに見返せます。",
    "H2_TWO_FEATURES": "NotiKeepだけの2つの強み",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Image Timeline",
    "IMT_LEAD": "通知に届いた写真を、まとめて見返せます。フォロー中チャンネルのYouTubeサムネやGoogle Photosの「○年前の今日」、LINEで送られた写真、ニュース、Instagramの投稿など、通知に写真が含まれるものは保存されます。",
    "IMT_ARIA": "Image Timeline画面から写真カードが飛び出す、3Dで傾いたスマホ",
    "IMT_CAPTION_HTML": 'YouTubeならサムネをタップ、そのまま好きなブラウザで再生できます（<a href="#browser-choice" style="color:inherit;text-decoration:underline;">Pro機能：下部</a>）。',
    "YT_TITLE": "YouTube通知を、好きなブラウザで",
    "YT_LEAD": "保存したYouTube通知をタップ → Chrome、Firefox、Brave等、お好きなブラウザで再生できます（Pro版のみ）。",
    "YT_IMG_ALT": "YouTube通知のブラウザ選択ダイアログ（Chrome、Firefox、Brave）",
    "YT_CAPTION": "",
    "H2_WHAT_YOU_GET": "できること",
    "F1_T": "Image Timeline",
    "F1_P": "通知に届いた写真を日付ごとに振り返り。",
    "F2_T": "YouTubeを好きなブラウザで",
    "F2_P": "YouTube通知を任意のブラウザで開く。",
    "F3_T": "スマートノイズフィルタ",
    "F3_P": "進捗バー、常駐通知、システム通知は自動で除外。",
    "F4_T": "ブックマーク",
    "F4_P": "大事な通知に⭐を。無料版でも期限なしで残せます。",
    "F5_T": "画像付きバックアップ",
    "F5_P": "アーカイブと画像をまとめてZIPに。機種変更しても引き継げます。",
    "F6_T": "カスタムテーマ",
    "F6_P": "アプリ画面を好きな配色に変更できます。",
    "F7_T": "アプリ別ベル制御",
    "F7_P": "通知はサイレントに保存。",
    "F8_T": "全文検索",
    "F8_P": "通知の中身からキーワード検索。Free版: 30日、Pro版: 全期間。",
    "F9_T": "12言語対応",
    "F9_P": "英語、日本語、한국어、中文、Español、Français、Deutsch ほか。",
    "H2_PRICING": "料金",
    "BEST_VALUE_LABEL": "おすすめ",
    "PRICE_MONTHLY": "月額",
    "PER_MO": "/月",
    "PRICE_NOTE_MONTHLY": "いつでも解約OK",
    "PRICE_YEARLY": "年額",
    "PER_YR": "/年",
    "PRICE_NOTE_YEARLY": "月額より約16%おトク",
    "PRICE_LIFETIME": "買い切り",
    "PRICE_NOTE_LIFETIME": "1回払いきり、サブスクなし",
    "PRICING_DISCLAIMER": "表示価格はUSDです。Google Playの購入画面では現地通貨に換算されて表示されます。",
    "TRIAL_BANNER_HTML": "まずは7日間お試し無料。トライアル終了時の課金はありません。",
    "H3_FREE_VS_PRO": "Free版とPro版の違い",
    "TBL_FEATURE": "機能",
    "TBL_FREE": "Free版",
    "TBL_PRO": "Pro版",
    "TBL_R1": "通知のアーカイブ",
    "TBL_R2": "画像の保存（詳細画面）",
    "TBL_R3": "スマートノイズフィルタ",
    "TBL_R4_LABEL": "保存期間",
    "TBL_R4_FREE": "30日（固定）",
    "TBL_R4_PRO": "30日〜無制限（自由設定）",
    "TBL_R5_LABEL": "検索",
    "TBL_R5_FREE": "直近30日",
    "TBL_R5_PRO": "全期間",
    "TBL_R6_LABEL": "ブックマーク・ミュート・ブロック",
    "TBL_R6_FREE": "各5件",
    "TBL_R6_PRO": "無制限",
    "TBL_R7": "Image Timeline（画像グリッド）",
    "TBL_R8": "YouTubeを好きなブラウザで",
    "TBL_R9": "バックアップ（画像付き）",
    "TBL_R10_LABEL": "カスタムテーマ",
    "TBL_R10_PRO": "3スロット",
    "CTA_TRY_FREE": "7日間無料で試す",
    "H2_FIT": "NotiKeep、合うかも？",
    "FIT_GREAT_TITLE": "こんな人に",
    "FIT_GREAT_1": "必要な通知をうっかり消して後悔したことがある",
    "FIT_GREAT_2": "メッセージアプリで送られてくる写真を残しておきたい",
    "FIT_GREAT_3": "LINE、WhatsApp、SMS、Gmailの通知をオフラインで残したい",
    "FIT_GREAT_4": "YouTubeアプリのShortsに毎回吸い込まれるのが嫌",
    "FIT_GREAT_5": "データはクラウドより端末内に置いておきたい",
    "FIT_SKIP_TITLE": "こんな人はスキップ",
    "FIT_SKIP_1": "Android標準の24時間履歴で十分",
    "FIT_SKIP_2": "",
    "FIT_SKIP_3": "",
    "FIT_SKIP_4": "",
    "H2_FAQ": "FAQ",
    "FAQ1_Q": "インストール前の通知も見られますか？",
    "FAQ1_A": "<strong>見られません。</strong> NotiKeepはインストール後＋通知アクセス許可後に届いた通知だけを保存します。",
    "FAQ2_Q": "対応Androidバージョンは？",
    "FAQ2_A": "Android 9.0以降に対応しています。",
    "FAQ3_Q": "ストレージはどのくらい使いますか？",
    "FAQ3_A": "テキスト通知は非常に小さく、数MBで何ヶ月分も保存できます。容量を使うのは画像で、保存される写真は20〜80KB程度、月に画像付き通知が1000件来るヘビーユーザーで30〜80MBくらいです。ストレージ容量が気になる場合は、保存日時設定を短くすれば安心です。",
    "FAQ4_Q": "アンインストールしたらデータは？",
    "FAQ4_A": "通知、画像、設定、ブックマークなどNotiKeepのデータは端末内に保存されますので、アンインストールをすると削除されます。再インストールや機種変更でも残しておきたい場合は、画像付きバックアップ、復元（Pro機能）をご検討ください。",
    "FAQ5_Q": "必要な権限は？",
    "FAQ5_A": "通知へのアクセスのみです。位置情報、連絡先などにはアクセスはしません。",
    "FAQ6_Q": "",
    "FAQ6_A": "",
    "FAQ7_Q": "データはエクスポートできますか？",
    "FAQ7_A": "Pro版でZIPを作成できます。データベース、保存済み画像、ブックマーク、ミュートリストなどの設定をまとめて新しい端末でもワンステップで復元できます。保存先は指定できます。",
    "FAQ8_Q": "7日トライアルが終わったら？",
    "FAQ8_A": "Free版に戻ります。自動更新はありません。Pro版が必要な場合は、アップグレード画面からお願いします。",
    "FAQ9_Q": "バッテリーや動作への影響は？",
    "FAQ9_A": "NotiKeepは通知が届いた瞬間だけ動きます。大容量の電池を消費し続けることはありません。",
    "FAQ10_Q": "通知の保存先は？",
    "FAQ10_A": "データはすべて端末内に保存します。バックアップも、自分で選んだ保存先に置かれるだけです。",
    "H2_RECENT": "最近のアップデート",
    "CL_127": "リリース版での開発用通知ダンプの書き出しを停止。既存ダンプはアップグレード時に自動削除",
    "CL_126": "Google Playからインストール時、システム言語に関係なく12言語が安定動作するように修正",
    "CL_125": "言語の選択がアプリ全体で一貫するよう改善（混在表示を解消）",
    "CL_124": "別言語の端末で取ったバックアップを復元してもUIが崩れない",
    "CL_123": "言語切替後の設定画面ラベルが、選んだ言語のままで維持されるように",
    "EARLIER_LABEL": "それ以前の主なマイルストーン",
    "EARLY_1": "Image Timeline — 通知に届いた写真をすべて振り返り",
    "EARLY_2": "YouTubeブラウザ選択 — 保存したYouTube通知をChrome、Firefox、Braveで",
    "EARLY_3": "バックアップ＆復元 — 画像も含めて1つのZIPで持ち運べる",
    "EARLY_4": "12言語対応 — 英語、日本語、한국어、中文 (简/繁)、Español、Français、Deutsch、Italiano、Português、Русскийほか",
    "EARLY_5": "スマートノイズフィルタ — 進捗バー、常駐通知、システム通知を自動で除外",
    "FINAL_CTA_H2": "通知はNotiKeepに",
    "FINAL_CTA_P": "7日間無料で試せます。",
    "FOOTER_MADE_BY": 'NotiKeepは <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a> が作っています',
    "FOOTER_PLAY": "Google Playで見る",
    "FOOTER_PRIVACY": "プライバシーポリシー",
    "FOOTER_SUPPORT": "サポート",
    "FOOTER_DISCLOSURE": "",
},

# =============================================================
# ko (Korean)
# =============================================================
"ko": {
    "F10_T": "대화 보기",
    "F10_P": "메시지 앱을 보낸 사람별 대화로. 사진도 대화 안에 그대로.",
    "PV_HEADING": "실제 작동 모습",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — 알림 기록',
    "META_DESCRIPTION": '사진을 포함한 알림을 저장합니다. YouTube 알림은 원하는 브라우저에서 열 수 있습니다. 7일 동안 모든 기능을 무료로 이용 가능. 광고 없음, 데이터는 기기 내에만 저장.',
    "OG_TITLE": 'NotiKeep — 알림 기록',
    "OG_DESCRIPTION": '사진을 포함한 알림을 저장. YouTube 알림은 원하는 브라우저에서. 7일 무료, 광고 없음, 데이터는 기기 내에만.',
    "HERO_H1_HTML": 'NotiKeep과 함께 <span class="accent">저장</span>',
    "HERO_TAGLINE": '사진, 인증 코드, 메시지 — 원하는 만큼 보관할 수 있습니다.',
    "HERO_IMG_ALT": "NotiKeep 메인 화면 — WhatsApp, Instagram, YouTube, Gmail 등의 알림 표시",
    "CTA_GET": "Google Play에서 받기",
    "TRIAL_NOTE": '',
    "H2_PAIN": '이런 일, 있으셨죠?',
    "PAIN_1": '친구가 카카오톡으로 보낸 사진 — 알림을 스와이프한 순간 사라짐',
    "PAIN_2": '',
    "PAIN_3": '「업로드 중…」「백그라운드에서 실행 중」 — 보고 싶지 않은 알림으로 가득한 알림창',
    "PAIN_4": '반쯤 졸면서 본 DM — 이제 어디에도 없음',
    "PAIN_OUTRO": 'NotiKeep이 보관합니다.',
    "H2_HOW": "사용 방법",
    "STEP1_TITLE": "설치 후 알림 접근 권한 부여",
    "STEP1_BODY": '먼저 알림 접근을 허용해 주세요. 앱이 들어오는 알림을 읽기 위해 필요합니다.',
    "STEP2_TITLE": "평소처럼 폰을 사용",
    "STEP2_IMG_ALT": "NotiKeep 메인 화면, 앱별 벨 제어",
    "STEP2_BODY": 'NotiKeep은 백그라운드에서 동작합니다. 배터리 최적화는 끄는 것을 권장합니다.',
    "STEP3_TITLE": '키워드로 검색',
    "STEP3_IMG_ALT": "NotiKeep에서 알림을 스와이프해 보관",
    "STEP3_BODY": '전문 검색으로 어떤 알림이든 찾을 수 있습니다. 중요한 것은 북마크해 두면 빠르게 다시 볼 수 있습니다.',
    "H2_TWO_FEATURES": "NotiKeep만의 두 가지 특징",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Image Timeline",
    "IMT_LEAD": '알림에 도착한 사진을 한꺼번에 다시 볼 수 있습니다. 구독 채널의 YouTube 썸네일, Google Photos의 「몇 년 전 오늘」, 카카오톡으로 받은 사진, 뉴스, Instagram 게시물 등 사진이 포함된 알림은 모두 보관됩니다.',
    "IMT_ARIA": "Image Timeline 화면에서 사진 카드가 날아 나오는 3D로 기울어진 폰",
    "IMT_CAPTION_HTML": 'YouTube 썸네일을 탭하면 원하는 브라우저에서 바로 재생됩니다 (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">Pro 기능: 하단</a>).',
    "YT_TITLE": "YouTube 알림을 원하는 브라우저로",
    "YT_LEAD": '저장된 YouTube 알림을 탭하면 Chrome, Firefox, Brave 등 원하는 브라우저에서 재생할 수 있습니다 (Pro 전용).',
    "YT_IMG_ALT": "YouTube 알림과 브라우저 선택 대화상자 (Chrome, Firefox, Brave)",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "사용 가능한 기능",
    "F1_T": "Image Timeline",
    "F1_P": "알림에 포함된 사진을 날짜별로 둘러보기.",
    "F2_T": "YouTube를 원하는 브라우저에서",
    "F2_P": "YouTube 알림을 원하는 브라우저에서 열기.",
    "F3_T": "스마트 노이즈 필터",
    "F3_P": "진행 표시줄, 포그라운드 서비스, 시스템 알림 — 자동 제거.",
    "F4_T": "북마크",
    "F4_P": '중요한 알림에 별표를. Free 버전에서도 만료되지 않습니다.',
    "F5_T": "이미지 포함 백업",
    "F5_P": '보관함과 이미지를 하나의 ZIP으로. 기기 변경 시에도 그대로.',
    "F6_T": "커스텀 테마",
    "F6_P": '앱 화면을 원하는 색상으로 변경할 수 있습니다.',
    "F7_T": "앱별 벨 제어",
    "F7_P": '알림은 조용히 보관됩니다.',
    "F8_T": "전체 텍스트 검색",
    "F8_P": '알림 내용으로 키워드 검색. Free 버전: 30일, Pro 버전: 전체.',
    "F9_T": "12개 언어 지원",
    "F9_P": "영어, 日本語, 한국어, 中文, Español, Français, Deutsch 외.",
    "H2_PRICING": "가격",
    "BEST_VALUE_LABEL": "추천",
    "PRICE_MONTHLY": "월간",
    "PER_MO": "/월",
    "PRICE_NOTE_MONTHLY": "언제든 해지 가능",
    "PRICE_YEARLY": "연간",
    "PER_YR": "/년",
    "PRICE_NOTE_YEARLY": "월간 대비 약 16% 할인",
    "PRICE_LIFETIME": "평생",
    "PRICE_NOTE_LIFETIME": "1회 결제, 구독 없음",
    "PRICING_DISCLAIMER": "표시된 가격은 USD 기준입니다. Google Play 결제 화면에서는 현지 통화로 환산되어 표시됩니다.",
    "TRIAL_BANNER_HTML": '먼저 7일 무료 체험. 체험 종료 시 결제는 없습니다.',
    "H3_FREE_VS_PRO": 'Free 버전과 Pro 버전의 차이',
    "TBL_FEATURE": "기능",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "알림 보관함",
    "TBL_R2": "이미지 보관 (상세 보기)",
    "TBL_R3": "스마트 노이즈 필터",
    "TBL_R4_LABEL": "보관 기간",
    "TBL_R4_FREE": "30일 (고정)",
    "TBL_R4_PRO": "설정 가능 · 30일 → 무제한",
    "TBL_R5_LABEL": "검색",
    "TBL_R5_FREE": "최근 30일",
    "TBL_R5_PRO": "전체 보관함",
    "TBL_R6_LABEL": "북마크 · 음소거 · 앱 차단",
    "TBL_R6_FREE": "각 5개",
    "TBL_R6_PRO": "무제한",
    "TBL_R7": "Image Timeline (이미지 그리드)",
    "TBL_R8": "YouTube를 원하는 브라우저에서",
    "TBL_R9": "이미지 포함 백업",
    "TBL_R10_LABEL": "커스텀 테마",
    "TBL_R10_PRO": "3슬롯",
    "CTA_TRY_FREE": '7일 무료로 체험',
    "H2_FIT": "NotiKeep, 당신에게 맞을까요?",
    "FIT_GREAT_TITLE": "잘 맞는 분…",
    "FIT_GREAT_1": "필요한 알림을 실수로 스와이프해 지우고 후회한 적이 있는 분",
    "FIT_GREAT_2": "메시징 앱으로 친구가 보낸 사진을 보관하고 싶은 분",
    "FIT_GREAT_3": "카카오톡, WhatsApp, SMS, Gmail 알림을 오프라인으로 기록하고 싶은 분",
    "FIT_GREAT_4": "YouTube 앱이 알림을 탭할 때마다 Shorts로 끌고 가는 게 지긋지긋한 분",
    "FIT_GREAT_5": "데이터를 누군가의 클라우드가 아니라 기기 내에만 두고 싶은 분",
    "FIT_SKIP_TITLE": "건너뛰셔도 좋은 분…",
    "FIT_SKIP_1": "Android 기본 24시간 알림 기록으로 충분한 분",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "FAQ",
    "FAQ1_Q": '설치하기 전의 알림도 볼 수 있나요?',
    "FAQ1_A": '<strong>볼 수 없습니다.</strong> NotiKeep은 설치 후 알림 접근 권한이 부여된 이후에 도착한 알림만 저장할 수 있습니다.',
    "FAQ2_Q": '지원하는 Android 버전은?',
    "FAQ2_A": 'Android 9.0 이상을 지원합니다.',
    "FAQ3_Q": "저장 용량은 얼마나 사용하나요?",
    "FAQ3_A": '텍스트 알림은 매우 작아서 몇 MB로 몇 달치를 저장할 수 있습니다. 용량을 차지하는 것은 이미지로, 저장된 사진은 약 20–80 KB입니다. 월 1,000건의 이미지가 있는 알림을 받는 헤비 유저도 약 30–80 MB 정도입니다. 저장 공간이 걱정된다면 보관 기간을 줄이세요.',
    "FAQ4_Q": "삭제하면 데이터는 어떻게 되나요?",
    "FAQ4_A": '알림, 이미지, 설정, 북마크 등 NotiKeep의 데이터는 기기 내에 저장되므로, 앱을 삭제하면 함께 삭제됩니다. 재설치나 기기 변경 후에도 보관하고 싶다면, 미리 이미지 포함 백업, 복원 (Pro 기능)을 검토해 주세요.',
    "FAQ5_Q": "어떤 권한이 필요한가요?",
    "FAQ5_A": '알림 접근만 사용합니다. 위치 정보, 연락처 등에는 접근하지 않습니다.',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "데이터를 내보낼 수 있나요?",
    "FAQ7_A": 'Pro 버전에서 ZIP을 만들 수 있습니다. 데이터베이스, 저장된 이미지, 북마크, 음소거 목록 등 설정을 한꺼번에 새 기기에서 한 번에 복원할 수 있습니다. 저장 위치는 지정할 수 있습니다.',
    "FAQ8_Q": "7일 체험 종료 후엔 어떻게 되나요?",
    "FAQ8_A": 'Free 버전으로 돌아갑니다. 자동 갱신은 없습니다. Pro 기능이 필요한 경우, 업그레이드 화면에서 직접 선택해 주세요.',
    "FAQ9_Q": "배터리 소모나 폰이 느려지나요?",
    "FAQ9_A": 'NotiKeep은 알림이 도착한 순간에만 동작합니다. 배터리를 계속 소비하지 않습니다.',
    "FAQ10_Q": '알림은 어디에 저장되나요?',
    "FAQ10_A": '데이터는 모두 기기 내에 저장됩니다. 백업도 직접 선택한 경로에만 저장됩니다.',
    "H2_RECENT": "최근 업데이트",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": '알림은 NotiKeep에',
    "FINAL_CTA_P": '7일 무료로 사용해 보세요.',
    "FOOTER_MADE_BY": 'NotiKeep은 <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a>가 만들었습니다',
    "FOOTER_PLAY": "Google Play에서 보기",
    "FOOTER_PRIVACY": "개인정보처리방침",
    "FOOTER_SUPPORT": "지원",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# zh-CN (Simplified Chinese)
# =============================================================
"zh-CN": {
    "F10_T": "对话视图",
    "F10_P": "即时通讯应用按发送者分组显示为对话，照片直接显示在对话中。",
    "PV_HEADING": "实际效果",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — 通知历史记录',
    "META_DESCRIPTION": '保留含图片的通知。在任意浏览器打开 YouTube 通知。7 天内免费使用全部功能。无广告,数据全部留在本地。',
    "OG_TITLE": 'NotiKeep — 通知历史记录',
    "OG_DESCRIPTION": '保留含图片的通知。任意浏览器打开 YouTube 通知。7 天免费,无广告,数据全部留在本地。',
    "HERO_H1_HTML": '用 NotiKeep <span class="accent">保留</span>',
    "HERO_TAGLINE": '图片、验证码、消息 — 想保留多久就保留多久。',
    "HERO_IMG_ALT": "NotiKeep 主画面 — 显示来自 WhatsApp、Instagram、YouTube、Gmail 等的通知",
    "CTA_GET": "在 Google Play 获取",
    "TRIAL_NOTE": '',
    "H2_PAIN": '这种事,你也遇到过吧?',
    "PAIN_1": '朋友刚通过微信发来的照片 — 滑掉通知的瞬间就消失了',
    "PAIN_2": '',
    "PAIN_3": '「上传中…」「应用正在后台运行」— 通知栏被你根本不想看的通知塞满',
    "PAIN_4": '半睡半醒时扫了一眼的私信 — 现在哪里都找不到',
    "PAIN_OUTRO": 'NotiKeep 帮你保留。',
    "H2_HOW": "使用方法",
    "STEP1_TITLE": "安装并授予通知访问权限",
    "STEP1_BODY": '首先,允许通知访问权限。应用读取传入的通知需要它。',
    "STEP2_TITLE": "正常使用手机",
    "STEP2_IMG_ALT": "NotiKeep 主画面,按应用控制铃声",
    "STEP2_BODY": 'NotiKeep 在后台运行。建议关闭电池优化。',
    "STEP3_TITLE": '用关键词搜索',
    "STEP3_IMG_ALT": "在 NotiKeep 中滑动通知归档",
    "STEP3_BODY": '全文搜索查找任何通知。重要的可以收藏,以便快速回看。',
    "H2_TWO_FEATURES": "NotiKeep 独有的两大特色",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "图片时间线",
    "IMT_LEAD": '可以一次性回看通知里出现过的照片。关注频道的 YouTube 缩略图、Google Photos 的「几年前的今天」、微信收到的照片、新闻、Instagram 帖子等,只要通知中带图都会被保留。',
    "IMT_ARIA": "图片卡片从图片时间线画面飞出的 3D 倾斜手机",
    "IMT_CAPTION_HTML": '点击 YouTube 缩略图,可在你选择的浏览器中直接播放(<a href="#browser-choice" style="color:inherit;text-decoration:underline;">Pro 功能:下方</a>)。',
    "YT_TITLE": "YouTube 通知,你的浏览器",
    "YT_LEAD": '点击保存的 YouTube 通知,即可在 Chrome、Firefox、Brave 等你喜欢的浏览器中播放(仅 Pro 版)。',
    "YT_IMG_ALT": "YouTube 通知与浏览器选择对话框(显示 Chrome、Firefox、Brave)",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "你能获得",
    "F1_T": "图片时间线",
    "F1_P": "按日期浏览通知中出现过的所有图片。",
    "F2_T": "YouTube 任意浏览器",
    "F2_P": "在你选择的浏览器中打开 YouTube 通知。",
    "F3_T": "智能噪音过滤",
    "F3_P": "进度条、前台服务、系统通知 — 自动丢弃。",
    "F4_T": "收藏",
    "F4_P": '重要通知加星。免费版也不会过期。',
    "F5_T": "含图片备份",
    "F5_P": '归档和图片打包成一个 ZIP。换机也能延续。',
    "F6_T": "自定义主题",
    "F6_P": '应用界面可自定义配色。',
    "F7_T": "按应用控制铃声",
    "F7_P": '通知静默保存。',
    "F8_T": "全文搜索",
    "F8_P": '按内容关键词查找通知。免费版:30 天,Pro 版:全部。',
    "F9_T": "12 种语言",
    "F9_P": "英语、日语、한국어、中文、Español、Français、Deutsch 等。",
    "H2_PRICING": "价格",
    "BEST_VALUE_LABEL": "最划算",
    "PRICE_MONTHLY": "月付",
    "PER_MO": "/月",
    "PRICE_NOTE_MONTHLY": "随时取消",
    "PRICE_YEARLY": "年付",
    "PER_YR": "/年",
    "PRICE_NOTE_YEARLY": "比月付便宜约 16%",
    "PRICE_LIFETIME": "买断",
    "PRICE_NOTE_LIFETIME": "一次性付款,无订阅",
    "PRICING_DISCLAIMER": "显示价格为美元。Google Play 结账时会按当地货币换算显示。",
    "TRIAL_BANNER_HTML": '先免费体验 7 天。试用结束不会扣费。',
    "H3_FREE_VS_PRO": '免费版与 Pro 版的区别',
    "TBL_FEATURE": "功能",
    "TBL_FREE": "免费",
    "TBL_PRO": "Pro",
    "TBL_R1": "通知归档",
    "TBL_R2": "图片保留(详情视图)",
    "TBL_R3": "智能噪音过滤",
    "TBL_R4_LABEL": "保留期",
    "TBL_R4_FREE": "30 天(固定)",
    "TBL_R4_PRO": "可配置 · 30 天 → 无限",
    "TBL_R5_LABEL": "搜索",
    "TBL_R5_FREE": "最近 30 天",
    "TBL_R5_PRO": "全部归档",
    "TBL_R6_LABEL": "收藏 · 静音 · 屏蔽",
    "TBL_R6_FREE": "各 5 个",
    "TBL_R6_PRO": "无限",
    "TBL_R7": "图片时间线(可浏览图片网格)",
    "TBL_R8": "在任意浏览器打开 YouTube",
    "TBL_R9": "含图片备份",
    "TBL_R10_LABEL": "自定义主题",
    "TBL_R10_PRO": "3 个槽位",
    "CTA_TRY_FREE": '7 天免费试用',
    "H2_FIT": "NotiKeep 适合你吗?",
    "FIT_GREAT_TITLE": "适合你,如果你…",
    "FIT_GREAT_1": "曾不小心滑掉需要的通知,然后后悔",
    "FIT_GREAT_2": "想保留消息应用里朋友发来的图片",
    "FIT_GREAT_3": "需要微信、WhatsApp、SMS 或 Gmail 通知的离线记录",
    "FIT_GREAT_4": "厌倦了 YouTube 应用每次点通知就把你拉进 Shorts",
    "FIT_GREAT_5": "在意把数据留在本地而不是别人的云端",
    "FIT_SKIP_TITLE": "可以跳过,如果你…",
    "FIT_SKIP_1": "对 Android 自带的 24 小时通知历史已满意",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "常见问题",
    "FAQ1_Q": '安装前的通知能看到吗?',
    "FAQ1_A": '<strong>看不到。</strong>NotiKeep 只会保存安装后获得通知访问权限以后到达的通知。',
    "FAQ2_Q": '支持哪些 Android 版本?',
    "FAQ2_A": 'Android 9.0 及以上。',
    "FAQ3_Q": "NotiKeep 占用多少存储?",
    "FAQ3_A": '文本通知非常小,几 MB 就能存几个月。占空间的主要是图片,每张保存的照片约 20–80 KB。每月收到 1,000 条带图通知的重度用户大约用 30–80 MB。担心占用空间的话,可以缩短保存期限。',
    "FAQ4_Q": "卸载后数据怎么办?",
    "FAQ4_A": '通知、图片、设置、收藏等 NotiKeep 的数据保存在设备内,卸载会一起删除。重装或换机后仍想保留,请先考虑使用含图片的备份与恢复(Pro 功能)。',
    "FAQ5_Q": "NotiKeep 需要什么权限?",
    "FAQ5_A": '仅通知访问。不获取位置、联系人等其他权限。',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "可以导出数据吗?",
    "FAQ7_A": 'Pro 版可以创建 ZIP。数据库、保存的图片、收藏、静音列表等设置一并打包,在新设备上一步复原。保存位置可指定。',
    "FAQ8_Q": "7 天试用结束后怎么办?",
    "FAQ8_A": '回到免费版。无自动续订。需要 Pro 功能时,从升级页面自行选择。',
    "FAQ9_Q": "会耗电或拖慢手机吗?",
    "FAQ9_A": 'NotiKeep 只在通知到达的瞬间工作。不会持续耗电。',
    "FAQ10_Q": '通知保存在哪里?',
    "FAQ10_A": '所有数据保存在设备内。备份也只保存到你指定的位置。',
    "H2_RECENT": "最近更新",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": '通知,交给 NotiKeep',
    "FINAL_CTA_P": '7 天免费试用。',
    "FOOTER_MADE_BY": 'NotiKeep 由 <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a> 制作',
    "FOOTER_PLAY": "Google Play 应用页",
    "FOOTER_PRIVACY": "隐私政策",
    "FOOTER_SUPPORT": "支持",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# zh-TW (Traditional Chinese)
# =============================================================
"zh-TW": {
    "F10_T": "對話檢視",
    "F10_P": "即時通訊應用程式依寄件者分組顯示為對話，照片直接顯示在對話中。",
    "PV_HEADING": "實際效果",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — 通知歷史記錄',
    "META_DESCRIPTION": '保留含圖片的通知。在任意瀏覽器開啟 YouTube 通知。7 天內免費使用全部功能。無廣告,資料全部留在本機。',
    "OG_TITLE": 'NotiKeep — 通知歷史記錄',
    "OG_DESCRIPTION": '保留含圖片的通知。任意瀏覽器開啟 YouTube 通知。7 天免費,無廣告,資料全部留在本機。',
    "HERO_H1_HTML": '用 NotiKeep <span class="accent">保留</span>',
    "HERO_TAGLINE": '圖片、驗證碼、訊息 — 想保留多久就保留多久。',
    "HERO_IMG_ALT": "NotiKeep 主畫面 — 顯示來自 WhatsApp、Instagram、YouTube、Gmail 等的通知",
    "CTA_GET": "在 Google Play 取得",
    "TRIAL_NOTE": '',
    "H2_PAIN": '這種事,你也遇到過吧?',
    "PAIN_1": '朋友剛用 LINE 傳來的照片 — 滑掉通知的瞬間就消失了',
    "PAIN_2": '',
    "PAIN_3": '「上傳中…」「應用程式正在背景執行」— 通知列被你根本不想看的通知塞滿',
    "PAIN_4": '半睡半醒時掃過的私訊 — 現在哪裡都找不到',
    "PAIN_OUTRO": 'NotiKeep 幫你保留。',
    "H2_HOW": "使用方式",
    "STEP1_TITLE": "安裝並授予通知存取權限",
    "STEP1_BODY": '首先,允許通知存取權限。應用程式讀取傳入的通知需要它。',
    "STEP2_TITLE": "照常使用手機",
    "STEP2_IMG_ALT": "NotiKeep 主畫面,按應用程式控制鈴聲",
    "STEP2_BODY": 'NotiKeep 在背景執行。建議關閉電池最佳化。',
    "STEP3_TITLE": '用關鍵字搜尋',
    "STEP3_IMG_ALT": "在 NotiKeep 中滑動通知封存",
    "STEP3_BODY": '全文搜尋查找任何通知。重要的可以收藏,以便快速回看。',
    "H2_TWO_FEATURES": "NotiKeep 獨有的兩大特色",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "圖片時間軸",
    "IMT_LEAD": '可以一次性回看通知裡出現過的照片。訂閱頻道的 YouTube 縮圖、Google Photos 的「幾年前的今天」、LINE 收到的照片、新聞、Instagram 貼文等,只要通知中帶圖都會被保留。',
    "IMT_ARIA": "圖片卡片從圖片時間軸畫面飛出的 3D 傾斜手機",
    "IMT_CAPTION_HTML": '點擊 YouTube 縮圖,可在你選擇的瀏覽器中直接播放(<a href="#browser-choice" style="color:inherit;text-decoration:underline;">Pro 功能:下方</a>)。',
    "YT_TITLE": "YouTube 通知,你的瀏覽器",
    "YT_LEAD": '點擊已儲存的 YouTube 通知,即可在 Chrome、Firefox、Brave 等你喜歡的瀏覽器中播放(僅 Pro 版)。',
    "YT_IMG_ALT": "YouTube 通知與瀏覽器選擇對話方塊(顯示 Chrome、Firefox、Brave)",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "你能獲得",
    "F1_T": "圖片時間軸",
    "F1_P": "按日期瀏覽通知中出現過的所有圖片。",
    "F2_T": "YouTube 任意瀏覽器",
    "F2_P": "在你選擇的瀏覽器中開啟 YouTube 通知。",
    "F3_T": "智慧雜訊過濾",
    "F3_P": "進度條、前景服務、系統通知 — 自動丟棄。",
    "F4_T": "書籤",
    "F4_P": '重要通知加星。免費版也不會過期。',
    "F5_T": "含圖片備份",
    "F5_P": '封存和圖片打包成一個 ZIP。換機也能延續。',
    "F6_T": "自訂主題",
    "F6_P": '應用程式介面可自訂配色。',
    "F7_T": "依應用程式控制鈴聲",
    "F7_P": '通知靜默儲存。',
    "F8_T": "全文搜尋",
    "F8_P": '依內容關鍵字尋找通知。免費版:30 天,Pro 版:全部。',
    "F9_T": "12 種語言",
    "F9_P": "英文、日文、한국어、中文、Español、Français、Deutsch 等。",
    "H2_PRICING": "價格",
    "BEST_VALUE_LABEL": "最划算",
    "PRICE_MONTHLY": "月付",
    "PER_MO": "/月",
    "PRICE_NOTE_MONTHLY": "隨時取消",
    "PRICE_YEARLY": "年付",
    "PER_YR": "/年",
    "PRICE_NOTE_YEARLY": "比月付便宜約 16%",
    "PRICE_LIFETIME": "買斷",
    "PRICE_NOTE_LIFETIME": "一次付款,無訂閱",
    "PRICING_DISCLAIMER": "顯示價格為美元。Google Play 結帳時會按當地貨幣換算顯示。",
    "TRIAL_BANNER_HTML": '先免費體驗 7 天。試用結束不會扣款。',
    "H3_FREE_VS_PRO": '免費版與 Pro 版的差異',
    "TBL_FEATURE": "功能",
    "TBL_FREE": "免費",
    "TBL_PRO": "Pro",
    "TBL_R1": "通知封存",
    "TBL_R2": "圖片保留(詳情檢視)",
    "TBL_R3": "智慧雜訊過濾",
    "TBL_R4_LABEL": "保留期",
    "TBL_R4_FREE": "30 天(固定)",
    "TBL_R4_PRO": "可設定 · 30 天 → 無限",
    "TBL_R5_LABEL": "搜尋",
    "TBL_R5_FREE": "最近 30 天",
    "TBL_R5_PRO": "全部封存",
    "TBL_R6_LABEL": "書籤 · 靜音 · 封鎖",
    "TBL_R6_FREE": "各 5 個",
    "TBL_R6_PRO": "無限",
    "TBL_R7": "圖片時間軸(可瀏覽圖片網格)",
    "TBL_R8": "在任意瀏覽器開啟 YouTube",
    "TBL_R9": "含圖片備份",
    "TBL_R10_LABEL": "自訂主題",
    "TBL_R10_PRO": "3 個槽位",
    "CTA_TRY_FREE": '7 天免費試用',
    "H2_FIT": "NotiKeep 適合你嗎?",
    "FIT_GREAT_TITLE": "適合你,如果你…",
    "FIT_GREAT_1": "曾不小心滑掉需要的通知,事後後悔",
    "FIT_GREAT_2": "想保留訊息應用裡朋友傳來的圖片",
    "FIT_GREAT_3": "需要 LINE、WhatsApp、SMS 或 Gmail 通知的離線紀錄",
    "FIT_GREAT_4": "厭倦了 YouTube 應用程式每次點通知就把你拉進 Shorts",
    "FIT_GREAT_5": "在意把資料留在本機而不是別人的雲端",
    "FIT_SKIP_TITLE": "可以略過,如果你…",
    "FIT_SKIP_1": "對 Android 內建的 24 小時通知歷史已滿意",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "常見問題",
    "FAQ1_Q": '安裝前的通知能看到嗎?',
    "FAQ1_A": '<strong>看不到。</strong>NotiKeep 只會儲存安裝後取得通知存取權限以後到達的通知。',
    "FAQ2_Q": '支援哪些 Android 版本?',
    "FAQ2_A": 'Android 9.0 及以上。',
    "FAQ3_Q": "NotiKeep 占用多少儲存?",
    "FAQ3_A": '文字通知非常小,幾 MB 就能存好幾個月。占空間的主要是圖片,每張保存的照片約 20–80 KB。每月收到 1,000 則帶圖通知的重度使用者大約用 30–80 MB。擔心占用空間的話,可以縮短保存期限。',
    "FAQ4_Q": "解除安裝後資料怎麼辦?",
    "FAQ4_A": '通知、圖片、設定、書籤等 NotiKeep 的資料保存在裝置內,解除安裝會一起刪除。重裝或換機後仍想保留,請先考慮使用含圖片的備份與還原(Pro 功能)。',
    "FAQ5_Q": "NotiKeep 需要什麼權限?",
    "FAQ5_A": '僅通知存取。不存取位置、聯絡人等其他權限。',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "可以匯出資料嗎?",
    "FAQ7_A": 'Pro 版可以建立 ZIP。資料庫、保存的圖片、書籤、靜音清單等設定一併打包,在新裝置上一步還原。儲存位置可指定。',
    "FAQ8_Q": "7 天試用結束後怎麼辦?",
    "FAQ8_A": '回到免費版。無自動續訂。需要 Pro 功能時,從升級頁面自行選擇。',
    "FAQ9_Q": "會耗電或拖慢手機嗎?",
    "FAQ9_A": 'NotiKeep 只在通知到達的瞬間工作。不會持續耗電。',
    "FAQ10_Q": '通知儲存在哪裡?',
    "FAQ10_A": '所有資料儲存在裝置內。備份也只儲存到你指定的位置。',
    "H2_RECENT": "最近更新",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": '通知,交給 NotiKeep',
    "FINAL_CTA_P": '7 天免費試用。',
    "FOOTER_MADE_BY": 'NotiKeep 由 <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a> 製作',
    "FOOTER_PLAY": "Google Play 應用頁",
    "FOOTER_PRIVACY": "隱私權政策",
    "FOOTER_SUPPORT": "支援",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# es (Spanish)
# =============================================================
"es": {
    "F10_T": "Vista de conversación",
    "F10_P": "Las apps de mensajería se ven como chats, agrupadas por remitente y con las fotos dentro de la conversación.",
    "PV_HEADING": "Míralo en acción",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — Historial de notificaciones',
    "META_DESCRIPTION": 'Guarda tus notificaciones, fotos incluidas. Abre las notificaciones de YouTube en cualquier navegador. 7 días gratis con todas las funciones. Sin anuncios, todos los datos en el dispositivo.',
    "OG_TITLE": 'NotiKeep — Historial de notificaciones',
    "OG_DESCRIPTION": 'Guarda tus notificaciones, fotos incluidas. Abre las notificaciones de YouTube en cualquier navegador. Prueba gratis 7 días. Sin anuncios, datos en el dispositivo.',
    "HERO_H1_HTML": 'Guarda con <span class="accent">NotiKeep</span>',
    "HERO_TAGLINE": 'Fotos, códigos, mensajes — guardados todo el tiempo que quieras.',
    "HERO_IMG_ALT": "NotiKeep — pantalla principal mostrando notificaciones de WhatsApp, Instagram, YouTube, Gmail y más",
    "CTA_GET": "Conseguir NotiKeep en Google Play",
    "TRIAL_NOTE": '',
    "H2_PAIN": '¿Te suena?',
    "PAIN_1": 'Esa foto que un amigo te acaba de enviar por WhatsApp — desaparecida en el momento que deslizaste',
    "PAIN_2": '',
    "PAIN_3": '"Subiendo…" "La aplicación se está ejecutando en segundo plano" — la barra llena de avisos que no querías ver',
    "PAIN_4": 'Ese DM que ojeaste medio dormido — ahora no se encuentra en ningún lado',
    "PAIN_OUTRO": 'NotiKeep los guarda por ti.',
    "H2_HOW": "Cómo funciona",
    "STEP1_TITLE": "Instala y concede el Acceso a Notificaciones",
    "STEP1_BODY": 'Primero, concede acceso a las notificaciones. La app lo necesita para leer las notificaciones entrantes.',
    "STEP2_TITLE": "Usa tu teléfono normalmente",
    "STEP2_IMG_ALT": "Vista del archivo principal de NotiKeep con control de campana por aplicación",
    "STEP2_BODY": 'NotiKeep funciona en segundo plano. Se recomienda desactivar la optimización de batería.',
    "STEP3_TITLE": 'Busca por palabra clave',
    "STEP3_IMG_ALT": "Deslizando una notificación para archivarla en NotiKeep",
    "STEP3_BODY": 'Búsqueda de texto completo para encontrar cualquier notificación. Marca como favoritas las importantes para acceder rápido.',
    "H2_TWO_FEATURES": "Dos funciones que distinguen a NotiKeep",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Línea de imágenes",
    "IMT_LEAD": 'Explora las fotos que llegaron en notificaciones — miniaturas de YouTube de los canales que sigues, recuerdos "en este día" de Google Photos, fotos enviadas por WhatsApp, miniaturas de noticias, publicaciones de Instagram. Si una notificación trae una foto, se guarda.',
    "IMT_ARIA": "Teléfono inclinado de lado con tarjetas de fotos saliendo de la pantalla de Línea de imágenes",
    "IMT_CAPTION_HTML": 'Toca una miniatura de YouTube para reproducirla directamente en el navegador que prefieras (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">función Pro: abajo</a>).',
    "YT_TITLE": "Notificaciones de YouTube, tu navegador",
    "YT_LEAD": 'Toca una notificación de YouTube guardada para reproducirla en Chrome, Firefox, Brave o cualquier otro navegador que prefieras (solo Pro).',
    "YT_IMG_ALT": "Notificación de YouTube con diálogo de selección de navegador mostrando Chrome, Firefox, Brave",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "Lo que obtienes",
    "F1_T": "Línea de imágenes",
    "F1_P": "Explora cada foto que llegó por una notificación, agrupada por fecha.",
    "F2_T": "YouTube en cualquier navegador",
    "F2_P": "Abre las notificaciones de YouTube en el navegador que prefieras.",
    "F3_T": "Filtro de ruido inteligente",
    "F3_P": "Barras de progreso, servicios en primer plano, pings del sistema — descartados automáticamente.",
    "F4_T": "Favoritos",
    "F4_P": 'Marca con estrella las importantes. Sin caducidad, también en la versión gratis.',
    "F5_T": "Copia de seguridad con imágenes",
    "F5_P": 'Archivo más imágenes en un ZIP. Sobrevive al cambio de dispositivo.',
    "F6_T": "Temas personalizados",
    "F6_P": 'Personaliza la paleta de colores de la app.',
    "F7_T": "Control de campana por app",
    "F7_P": 'Guarda las notificaciones en silencio.',
    "F8_T": "Búsqueda de texto completo",
    "F8_P": 'Encuentra cualquier notificación por contenido. Gratis: 30 días, Pro: para siempre.',
    "F9_T": "12 idiomas",
    "F9_P": "Inglés, 日本語, 한국어, 中文, Español, Français, Deutsch y más.",
    "H2_PRICING": "Precios",
    "BEST_VALUE_LABEL": "Mejor valor",
    "PRICE_MONTHLY": "Mensual",
    "PER_MO": "/mes",
    "PRICE_NOTE_MONTHLY": "Cancela cuando quieras",
    "PRICE_YEARLY": "Anual",
    "PER_YR": "/año",
    "PRICE_NOTE_YEARLY": "~16% menos que la tarifa mensual",
    "PRICE_LIFETIME": "De por vida",
    "PRICE_NOTE_LIFETIME": "Pago único, sin suscripción",
    "PRICING_DISCLAIMER": "Los precios se muestran en USD. Google Play muestra el equivalente en tu moneda local en el momento de pagar.",
    "TRIAL_BANNER_HTML": 'Empieza con 7 días gratis. Sin cargo al finalizar la prueba.',
    "H3_FREE_VS_PRO": 'Free vs Pro',
    "TBL_FEATURE": "Función",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "Archivo de notificaciones",
    "TBL_R2": "Conservación de imágenes (vista detalle)",
    "TBL_R3": "Filtro de ruido inteligente",
    "TBL_R4_LABEL": "Retención",
    "TBL_R4_FREE": "30 días (fijo)",
    "TBL_R4_PRO": "Configurable · 30 días → ilimitado",
    "TBL_R5_LABEL": "Búsqueda",
    "TBL_R5_FREE": "Últimos 30 días",
    "TBL_R5_PRO": "Todo el archivo",
    "TBL_R6_LABEL": "Favoritos · Silenciar · Bloquear",
    "TBL_R6_FREE": "5 cada uno",
    "TBL_R6_PRO": "Ilimitado",
    "TBL_R7": "Línea de imágenes (cuadrícula navegable)",
    "TBL_R8": "Abrir YouTube en cualquier navegador",
    "TBL_R9": "Copia con imágenes",
    "TBL_R10_LABEL": "Temas personalizados",
    "TBL_R10_PRO": "3 espacios",
    "CTA_TRY_FREE": 'Prueba gratis 7 días',
    "H2_FIT": "¿Es NotiKeep para ti?",
    "FIT_GREAT_TITLE": "Buen ajuste si tú…",
    "FIT_GREAT_1": "Alguna vez deslizaste una notificación que necesitabas y te arrepentiste al instante",
    "FIT_GREAT_2": "Quieres conservar las fotos que tus amigos envían por apps de mensajería",
    "FIT_GREAT_3": "Necesitas registros offline de notificaciones de WhatsApp, Messenger, SMS o Gmail",
    "FIT_GREAT_4": "Estás cansado de que la app de YouTube te arrastre a Shorts cada vez que tocas una notificación",
    "FIT_GREAT_5": "Te importa mantener tus datos en el dispositivo, no en la nube de alguien más",
    "FIT_SKIP_TITLE": "Mejor sáltalo si tú…",
    "FIT_SKIP_1": "Te basta con el historial de notificaciones de 24 horas integrado en Android",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "FAQ",
    "FAQ1_Q": '¿Puede NotiKeep ver notificaciones recibidas antes de instalarlo?',
    "FAQ1_A": '<strong>No.</strong> NotiKeep solo guarda notificaciones que llegan después de instalarse y conceder el acceso a notificaciones.',
    "FAQ2_Q": '¿Qué versiones de Android admite?',
    "FAQ2_A": 'Android 9.0 y posteriores.',
    "FAQ3_Q": "¿Cuánto almacenamiento usa NotiKeep?",
    "FAQ3_A": 'Las notificaciones de texto son diminutas — unos pocos MB cubren meses. El espacio lo ocupan las imágenes: cada foto guardada pesa unos 20–80 KB. Un usuario intensivo con 1.000 notificaciones con imagen al mes usa ~30–80 MB. Si te preocupa, acorta el periodo de retención.',
    "FAQ4_Q": "¿Qué pasa con mis datos si desinstalo?",
    "FAQ4_A": 'Todos los datos de NotiKeep — notificaciones, imágenes, preferencias, favoritos — se guardan en el dispositivo, así que al desinstalar se borran. Si quieres conservar el archivo al reinstalar o cambiar de teléfono, considera la copia con imágenes y restauración (función Pro).',
    "FAQ5_Q": "¿Qué permisos necesita NotiKeep?",
    "FAQ5_A": 'Solo acceso a notificaciones. Sin ubicación, sin contactos, sin otros accesos.',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "¿Puedo exportar mis datos?",
    "FAQ7_A": 'Pro crea un ZIP con la base de datos, imágenes guardadas, favoritos, listas de silenciados y ajustes — todo junto. Restaura en un teléfono nuevo en un solo paso. La ubicación de guardado la eliges tú.',
    "FAQ8_Q": "¿Qué ocurre al final de la prueba de 7 días?",
    "FAQ8_A": 'Vuelves a Free. Sin renovación automática. Si quieres Pro, elige un plan en la pantalla de actualización.',
    "FAQ9_Q": "¿Consume batería o ralentiza el teléfono?",
    "FAQ9_A": 'NotiKeep solo trabaja cuando llega una notificación. No se queda consumiendo batería.',
    "FAQ10_Q": '¿Dónde se guardan mis datos?',
    "FAQ10_A": 'Todos los datos quedan en el dispositivo. Las copias van solo a la ruta que tú elijas.',
    "H2_RECENT": "Actualizaciones recientes",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": 'Tus notificaciones, con NotiKeep',
    "FINAL_CTA_P": 'Prueba gratis 7 días.',
    "FOOTER_MADE_BY": 'NotiKeep está hecho por <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a>',
    "FOOTER_PLAY": "App en Google Play",
    "FOOTER_PRIVACY": "Política de privacidad",
    "FOOTER_SUPPORT": "Soporte",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# pt-BR (Portuguese — Brazilian)
# =============================================================
"pt": {
    "F10_T": "Visão de conversa",
    "F10_P": "Apps de mensagens aparecem como conversas, agrupadas por remetente e com as fotos dentro da conversa.",
    "PV_HEADING": "Veja em ação",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — Histórico de notificações',
    "META_DESCRIPTION": 'Salve suas notificações, fotos inclusas. Abra notificações do YouTube em qualquer navegador. 7 dias gratuitos com todos os recursos. Sem anúncios, todos os dados no aparelho.',
    "OG_TITLE": 'NotiKeep — Histórico de notificações',
    "OG_DESCRIPTION": 'Salve suas notificações, fotos inclusas. Abra notificações do YouTube em qualquer navegador. Teste grátis 7 dias. Sem anúncios, dados no aparelho.',
    "HERO_H1_HTML": 'Salve com <span class="accent">NotiKeep</span>',
    "HERO_TAGLINE": 'Fotos, códigos, mensagens — guardados pelo tempo que você quiser.',
    "HERO_IMG_ALT": "NotiKeep — tela principal mostrando notificações do WhatsApp, Instagram, YouTube, Gmail e mais",
    "CTA_GET": "Baixar NotiKeep no Google Play",
    "TRIAL_NOTE": '',
    "H2_PAIN": 'Já passou por isso?',
    "PAIN_1": 'Aquela foto que um amigo acabou de mandar pelo WhatsApp — sumiu no momento em que você deslizou',
    "PAIN_2": '',
    "PAIN_3": '"Enviando…" "O aplicativo está em execução em segundo plano" — a barra cheia de avisos que você nem queria ver',
    "PAIN_4": 'Aquela DM que você leu meio dormindo — agora não acha em lugar nenhum',
    "PAIN_OUTRO": 'O NotiKeep guarda para você.',
    "H2_HOW": "Como funciona",
    "STEP1_TITLE": "Instale e conceda Acesso a Notificações",
    "STEP1_BODY": 'Primeiro, conceda acesso às notificações. O app precisa disso para ler as notificações que chegam.',
    "STEP2_TITLE": "Use seu celular normalmente",
    "STEP2_IMG_ALT": "Tela principal do NotiKeep com controle de sino por aplicativo",
    "STEP2_BODY": 'O NotiKeep roda em segundo plano. Recomenda-se desativar a otimização de bateria.',
    "STEP3_TITLE": 'Pesquise por palavra-chave',
    "STEP3_IMG_ALT": "Deslizando uma notificação para arquivar no NotiKeep",
    "STEP3_BODY": 'Pesquisa em todo o texto para encontrar qualquer notificação. Marque como favoritas as importantes para acesso rápido.',
    "H2_TWO_FEATURES": "Duas funções que diferenciam o NotiKeep",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Linha do tempo de imagens",
    "IMT_LEAD": 'Explore as fotos que chegaram em notificações — miniaturas do YouTube dos canais que você segue, lembranças "neste dia" do Google Fotos, fotos enviadas pelo WhatsApp, miniaturas de notícias, postagens do Instagram. Se uma notificação trouxer uma foto, ela é salva.',
    "IMT_ARIA": "Celular inclinado de lado com cartões de fotos saindo da tela da Linha do tempo de imagens",
    "IMT_CAPTION_HTML": 'Toque em uma miniatura do YouTube para tocá-la direto no navegador que preferir (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">recurso Pro: abaixo</a>).',
    "YT_TITLE": "Notificações do YouTube, no seu navegador",
    "YT_LEAD": 'Toque em uma notificação do YouTube salva para tocá-la no Chrome, Firefox, Brave ou qualquer outro navegador que preferir (apenas Pro).',
    "YT_IMG_ALT": "Notificação do YouTube com diálogo de seleção de navegador mostrando Chrome, Firefox, Brave",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "O que você ganha",
    "F1_T": "Linha do tempo de imagens",
    "F1_P": "Navegue por cada foto que chegou em uma notificação, agrupada por data.",
    "F2_T": "YouTube em qualquer navegador",
    "F2_P": "Abra notificações do YouTube no navegador da sua escolha.",
    "F3_T": "Filtro de ruído inteligente",
    "F3_P": "Barras de progresso, serviços em primeiro plano, pings do sistema — descartados automaticamente.",
    "F4_T": "Favoritos",
    "F4_P": 'Marque as importantes. Sem expiração, mesmo no plano gratuito.',
    "F5_T": "Backup com imagens",
    "F5_P": 'Arquivo mais imagens em um ZIP. Sobrevive à troca de aparelho.',
    "F6_T": "Temas personalizados",
    "F6_P": 'Personalize as cores do app.',
    "F7_T": "Controle de sino por app",
    "F7_P": 'Salva as notificações em silêncio.',
    "F8_T": "Pesquisa por texto completo",
    "F8_P": 'Encontre qualquer notificação pelo conteúdo. Free: 30 dias, Pro: para sempre.',
    "F9_T": "12 idiomas",
    "F9_P": "Inglês, 日本語, 한국어, 中文, Español, Français, Deutsch e mais.",
    "H2_PRICING": "Preços",
    "BEST_VALUE_LABEL": "Melhor custo",
    "PRICE_MONTHLY": "Mensal",
    "PER_MO": "/mês",
    "PRICE_NOTE_MONTHLY": "Cancele quando quiser",
    "PRICE_YEARLY": "Anual",
    "PER_YR": "/ano",
    "PRICE_NOTE_YEARLY": "~16% mais barato que o mensal",
    "PRICE_LIFETIME": "Vitalício",
    "PRICE_NOTE_LIFETIME": "Pagamento único, sem assinatura",
    "PRICING_DISCLAIMER": "Preços exibidos em USD. O Google Play mostra o equivalente em sua moeda local no momento da compra.",
    "TRIAL_BANNER_HTML": 'Comece com 7 dias gratuitos. Sem cobrança no fim do teste.',
    "H3_FREE_VS_PRO": 'Free vs Pro',
    "TBL_FEATURE": "Recurso",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "Arquivo de notificações",
    "TBL_R2": "Preservação de imagens (visualização)",
    "TBL_R3": "Filtro de ruído inteligente",
    "TBL_R4_LABEL": "Retenção",
    "TBL_R4_FREE": "30 dias (fixo)",
    "TBL_R4_PRO": "Configurável · 30 dias → ilimitado",
    "TBL_R5_LABEL": "Pesquisa",
    "TBL_R5_FREE": "Últimos 30 dias",
    "TBL_R5_PRO": "Arquivo inteiro",
    "TBL_R6_LABEL": "Favoritos · Silenciar · Bloquear",
    "TBL_R6_FREE": "5 cada",
    "TBL_R6_PRO": "Ilimitado",
    "TBL_R7": "Linha do tempo de imagens (grade navegável)",
    "TBL_R8": "Abrir YouTube em qualquer navegador",
    "TBL_R9": "Backup com imagens",
    "TBL_R10_LABEL": "Temas personalizados",
    "TBL_R10_PRO": "3 espaços",
    "CTA_TRY_FREE": 'Teste grátis 7 dias',
    "H2_FIT": "O NotiKeep é pra você?",
    "FIT_GREAT_TITLE": "Combina se você…",
    "FIT_GREAT_1": "Já passou o dedo numa notificação que precisava e se arrependeu na hora",
    "FIT_GREAT_2": "Quer guardar as fotos que amigos enviam por apps de mensagem",
    "FIT_GREAT_3": "Precisa de registros offline de notificações de WhatsApp, Telegram, SMS ou Gmail",
    "FIT_GREAT_4": "Cansou do app do YouTube te puxar para Shorts toda vez que você toca em uma notificação",
    "FIT_GREAT_5": "Se importa em manter seus dados no aparelho, não na nuvem de alguém",
    "FIT_SKIP_TITLE": "Pode pular se você…",
    "FIT_SKIP_1": "Está satisfeito com o histórico de notificações de 24 horas embutido no Android",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "FAQ",
    "FAQ1_Q": 'O NotiKeep consegue ver notificações recebidas antes de instalá-lo?',
    "FAQ1_A": '<strong>Não.</strong> O NotiKeep só salva notificações que chegam após a instalação e a concessão do acesso às notificações.',
    "FAQ2_Q": 'Quais versões do Android são suportadas?',
    "FAQ2_A": 'Android 9.0 e superiores.',
    "FAQ3_Q": "Quanto armazenamento o NotiKeep usa?",
    "FAQ3_A": 'Notificações de texto são minúsculas — alguns MB cobrem meses. O espaço fica com as imagens: cada foto salva tem cerca de 20–80 KB. Um usuário pesado com 1.000 notificações com imagem por mês usa ~30–80 MB. Se preocupar, encurte o período de retenção.',
    "FAQ4_Q": "O que acontece com meus dados se eu desinstalar?",
    "FAQ4_A": 'Todos os dados do NotiKeep — notificações, imagens, preferências, favoritos — ficam no aparelho, então a desinstalação apaga. Para manter ao reinstalar ou mudar de celular, considere o backup com imagens e restauração (recurso Pro).',
    "FAQ5_Q": "Que permissões o NotiKeep precisa?",
    "FAQ5_A": 'Apenas acesso a notificações. Sem localização, sem contatos, sem outros acessos.',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "Posso exportar meus dados?",
    "FAQ7_A": 'O Pro cria um ZIP com o banco de dados, imagens salvas, favoritos, listas de silenciados e configurações — tudo junto. Restaure em um celular novo em um passo. O local de salvamento é à sua escolha.',
    "FAQ8_Q": "O que acontece no fim do teste de 7 dias?",
    "FAQ8_A": 'Você volta para o Free. Sem renovação automática. Se quiser Pro, escolha um plano na tela de upgrade.',
    "FAQ9_Q": "Vai gastar bateria ou deixar o celular lento?",
    "FAQ9_A": 'O NotiKeep só trabalha quando uma notificação chega. Não fica consumindo bateria.',
    "FAQ10_Q": 'Onde meus dados ficam guardados?',
    "FAQ10_A": 'Todos os dados ficam no aparelho. Os backups vão apenas para o caminho que você escolher.',
    "H2_RECENT": "Atualizações recentes",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": 'Suas notificações, com NotiKeep',
    "FINAL_CTA_P": 'Teste grátis 7 dias.',
    "FOOTER_MADE_BY": 'NotiKeep é feito por <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a>',
    "FOOTER_PLAY": "App no Google Play",
    "FOOTER_PRIVACY": "Política de privacidade",
    "FOOTER_SUPPORT": "Suporte",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# fr (French)
# =============================================================
"fr": {
    "F10_T": "Vue conversation",
    "F10_P": "La messagerie s'affiche en discussions, par expéditeur, avec les photos directement dans la conversation.",
    "PV_HEADING": "NotiKeep en action",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — Historique des notifications',
    "META_DESCRIPTION": "Sauvegardez vos notifications, photos incluses. Ouvrez les notifications YouTube dans n'importe quel navigateur. 7 jours gratuits avec toutes les fonctionnalités. Sans publicité, données sur l'appareil.",
    "OG_TITLE": 'NotiKeep — Historique des notifications',
    "OG_DESCRIPTION": "Sauvegardez vos notifications, photos incluses. Ouvrez les notifications YouTube dans n'importe quel navigateur. Essai gratuit 7 jours. Sans pub, données sur l'appareil.",
    "HERO_H1_HTML": 'Sauvegardez avec <span class="accent">NotiKeep</span>',
    "HERO_TAGLINE": 'Photos, codes, messages — conservés aussi longtemps que vous le voulez.',
    "HERO_IMG_ALT": "NotiKeep — écran principal affichant les notifications de WhatsApp, Instagram, YouTube, Gmail et plus",
    "CTA_GET": "Obtenir NotiKeep sur Google Play",
    "TRIAL_NOTE": '',
    "H2_PAIN": 'Ça vous parle ?',
    "PAIN_1": "Cette photo qu'un ami vient d'envoyer sur WhatsApp — disparue dès que vous avez balayé",
    "PAIN_2": '',
    "PAIN_3": "« Téléversement… » « L'application s'exécute en arrière-plan » — votre barre saturée de notifications dont vous ne vouliez pas",
    "PAIN_4": 'Ce DM que vous avez parcouru à moitié endormi — introuvable maintenant',
    "PAIN_OUTRO": 'NotiKeep les garde pour vous.',
    "H2_HOW": "Comment ça marche",
    "STEP1_TITLE": "Installez et accordez l'Accès aux notifications",
    "STEP1_BODY": "D'abord, autorisez l'accès aux notifications. L'app en a besoin pour lire les notifications entrantes.",
    "STEP2_TITLE": "Utilisez votre téléphone normalement",
    "STEP2_IMG_ALT": "Vue principale de l'archive NotiKeep avec contrôle de cloche par application",
    "STEP2_BODY": "NotiKeep fonctionne en arrière-plan. Il est recommandé de désactiver l'optimisation de la batterie.",
    "STEP3_TITLE": 'Recherche par mot-clé',
    "STEP3_IMG_ALT": "Glissement d'une notification pour l'archiver dans NotiKeep",
    "STEP3_BODY": "Recherche en texte intégral pour retrouver n'importe quelle notification. Marquez les importantes en favoris pour y accéder rapidement.",
    "H2_TWO_FEATURES": "Deux fonctions qui distinguent NotiKeep",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Chronologie d'images",
    "IMT_LEAD": "Parcourez les photos arrivées dans des notifications — vignettes YouTube des chaînes que vous suivez, souvenirs « ce jour-là » de Google Photos, photos envoyées sur WhatsApp, vignettes d'articles, publications Instagram. Si une notification contient une photo, elle est conservée.",
    "IMT_ARIA": "Téléphone incliné de côté avec des cartes photo s'envolant de l'écran Chronologie d'images",
    "IMT_CAPTION_HTML": 'Touchez une vignette YouTube pour la lire directement dans le navigateur de votre choix (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">fonction Pro : ci-dessous</a>).',
    "YT_TITLE": "Notifications YouTube, votre navigateur",
    "YT_LEAD": 'Touchez une notification YouTube enregistrée pour la lire dans Chrome, Firefox, Brave ou tout autre navigateur de votre choix (Pro uniquement).',
    "YT_IMG_ALT": "Notification YouTube avec dialogue de choix de navigateur (Chrome, Firefox, Brave)",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "Ce que vous obtenez",
    "F1_T": "Chronologie d'images",
    "F1_P": "Parcourez chaque photo arrivée par une notification, regroupée par date.",
    "F2_T": "YouTube dans n'importe quel navigateur",
    "F2_P": "Ouvrez les notifications YouTube dans le navigateur de votre choix.",
    "F3_T": "Filtre de bruit intelligent",
    "F3_P": "Barres de progression, services en avant-plan, pings système — automatiquement écartés.",
    "F4_T": "Favoris",
    "F4_P": "Étoilez les importantes. Pas d'expiration, même en gratuit.",
    "F5_T": "Sauvegarde avec images",
    "F5_P": "Archive et images dans un ZIP. Survit au changement d'appareil.",
    "F6_T": "Thèmes personnalisés",
    "F6_P": "Personnalisez les couleurs de l'app.",
    "F7_T": "Cloche par application",
    "F7_P": 'Sauvegarde les notifications en silence.',
    "F8_T": "Recherche plein texte",
    "F8_P": "Trouvez n'importe quelle notification par contenu. Gratuit : 30 jours, Pro : pour toujours.",
    "F9_T": "12 langues",
    "F9_P": "Anglais, 日本語, 한국어, 中文, Español, Français, Deutsch et plus.",
    "H2_PRICING": "Tarifs",
    "BEST_VALUE_LABEL": "Meilleur rapport",
    "PRICE_MONTHLY": "Mensuel",
    "PER_MO": "/mois",
    "PRICE_NOTE_MONTHLY": "Annulable à tout moment",
    "PRICE_YEARLY": "Annuel",
    "PER_YR": "/an",
    "PRICE_NOTE_YEARLY": "~16 % moins cher que le mensuel",
    "PRICE_LIFETIME": "À vie",
    "PRICE_NOTE_LIFETIME": "Paiement unique, sans abonnement",
    "PRICING_DISCLAIMER": "Tarifs en USD. Google Play affiche l'équivalent dans votre devise locale au moment du paiement.",
    "TRIAL_BANNER_HTML": "Commencez par 7 jours gratuits. Aucun débit à la fin de l'essai.",
    "H3_FREE_VS_PRO": 'Gratuit vs Pro',
    "TBL_FEATURE": "Fonction",
    "TBL_FREE": "Gratuit",
    "TBL_PRO": "Pro",
    "TBL_R1": "Archive de notifications",
    "TBL_R2": "Conservation d'images (vue détaillée)",
    "TBL_R3": "Filtre de bruit intelligent",
    "TBL_R4_LABEL": "Rétention",
    "TBL_R4_FREE": "30 jours (fixe)",
    "TBL_R4_PRO": "Configurable · 30 jours → illimité",
    "TBL_R5_LABEL": "Recherche",
    "TBL_R5_FREE": "30 derniers jours",
    "TBL_R5_PRO": "Toute l'archive",
    "TBL_R6_LABEL": "Favoris · Sourdine · Blocage",
    "TBL_R6_FREE": "5 chacun",
    "TBL_R6_PRO": "Illimité",
    "TBL_R7": "Chronologie d'images (grille parcourable)",
    "TBL_R8": "Ouvrir YouTube dans n'importe quel navigateur",
    "TBL_R9": "Sauvegarde avec images",
    "TBL_R10_LABEL": "Thèmes personnalisés",
    "TBL_R10_PRO": "3 emplacements",
    "CTA_TRY_FREE": 'Essayez 7 jours gratuits',
    "H2_FIT": "NotiKeep est-il pour vous ?",
    "FIT_GREAT_TITLE": "Bon choix si vous…",
    "FIT_GREAT_1": "Avez déjà balayé une notification dont vous aviez besoin et l'avez regretté aussitôt",
    "FIT_GREAT_2": "Voulez conserver les photos que vos amis envoient via les apps de messagerie",
    "FIT_GREAT_3": "Avez besoin d'archives hors ligne des notifications WhatsApp, Messenger, SMS ou Gmail",
    "FIT_GREAT_4": "En avez assez que l'app YouTube vous attire dans Shorts à chaque tap sur une notification",
    "FIT_GREAT_5": "Tenez à garder vos données sur l'appareil, pas dans le cloud de quelqu'un d'autre",
    "FIT_SKIP_TITLE": "Passez votre tour si vous…",
    "FIT_SKIP_1": "Êtes content de l'historique de notifications de 24 h intégré à Android",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "FAQ",
    "FAQ1_Q": 'NotiKeep peut-il voir les notifications reçues avant son installation ?',
    "FAQ1_A": "<strong>Non.</strong> NotiKeep n'enregistre que les notifications qui arrivent après l'installation et l'octroi de l'accès aux notifications.",
    "FAQ2_Q": "Quelles versions d'Android sont prises en charge ?",
    "FAQ2_A": 'Android 9.0 et plus récent.',
    "FAQ3_Q": "Combien d'espace utilise NotiKeep ?",
    "FAQ3_A": "Les notifications texte sont minuscules — quelques Mo couvrent des mois. L'espace est pris par les images : chaque photo enregistrée pèse environ 20–80 Ko. Un usage intensif avec 1 000 notifications avec image par mois représente ~30–80 Mo. Si l'espace vous préoccupe, raccourcissez la durée de rétention.",
    "FAQ4_Q": "Que devient mon archive si je désinstalle ?",
    "FAQ4_A": "Toutes les données de NotiKeep — notifications, images, préférences, favoris — sont stockées sur l'appareil, donc la désinstallation les supprime. Pour les conserver lors d'une réinstallation ou d'un nouveau téléphone, envisagez la sauvegarde avec images et la restauration (fonction Pro).",
    "FAQ5_Q": "Quelles autorisations NotiKeep demande-t-il ?",
    "FAQ5_A": "Uniquement l'accès aux notifications. Pas de localisation, pas de contacts, pas d'autres accès.",
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "Puis-je exporter mes données ?",
    "FAQ7_A": "Le Pro crée un ZIP avec la base de données, les images conservées, les favoris, les listes de sourdines et les réglages — tout en un. Restauration sur un nouveau téléphone en un pas. L'emplacement de sauvegarde est à votre choix.",
    "FAQ8_Q": "Que se passe-t-il à la fin de l'essai de 7 jours ?",
    "FAQ8_A": "Vous repassez sur Free. Pas de renouvellement automatique. Si vous voulez Pro, choisissez un plan dans l'écran de mise à niveau.",
    "FAQ9_Q": "Cela vide-t-il la batterie ou ralentit-il le téléphone ?",
    "FAQ9_A": 'NotiKeep ne travaille que quand une notification arrive. Il ne reste pas à pomper la batterie.',
    "FAQ10_Q": 'Où mes données sont-elles stockées ?',
    "FAQ10_A": "Toutes les données restent sur l'appareil. Les sauvegardes vont uniquement vers un chemin que vous choisissez.",
    "H2_RECENT": "Mises à jour récentes",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": 'Vos notifications, avec NotiKeep',
    "FINAL_CTA_P": 'Essayez 7 jours gratuits.',
    "FOOTER_MADE_BY": 'NotiKeep est conçu par <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a>',
    "FOOTER_PLAY": "App sur Google Play",
    "FOOTER_PRIVACY": "Politique de confidentialité",
    "FOOTER_SUPPORT": "Support",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# de (German)
# =============================================================
"de": {
    "F10_T": "Unterhaltungsansicht",
    "F10_P": "Messaging-Apps erscheinen als Chatverläufe — nach Absender gruppiert, Fotos direkt in der Unterhaltung.",
    "PV_HEADING": "So funktioniert's",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — Benachrichtigungsverlauf',
    "META_DESCRIPTION": 'Speichere deine Benachrichtigungen samt Bildern. Öffne YouTube-Benachrichtigungen in jedem Browser. 7 Tage kostenlos mit allen Funktionen. Keine Werbung, alle Daten auf dem Gerät.',
    "OG_TITLE": 'NotiKeep — Benachrichtigungsverlauf',
    "OG_DESCRIPTION": 'Speichere deine Benachrichtigungen samt Bildern. YouTube-Benachrichtigungen in jedem Browser öffnen. 7 Tage kostenlos. Keine Werbung, Daten auf dem Gerät.',
    "HERO_H1_HTML": 'Speichern mit <span class="accent">NotiKeep</span>',
    "HERO_TAGLINE": 'Fotos, Codes, Nachrichten — so lange aufbewahrt, wie du willst.',
    "HERO_IMG_ALT": "NotiKeep — Hauptbildschirm mit Benachrichtigungen von WhatsApp, Instagram, YouTube, Gmail und mehr",
    "CTA_GET": "NotiKeep auf Google Play holen",
    "TRIAL_NOTE": '',
    "H2_PAIN": 'Kennst du das?',
    "PAIN_1": 'Das WhatsApp-Foto, das ein Freund gerade geschickt hat — weg, sobald du gewischt hast',
    "PAIN_2": '',
    "PAIN_3": '„Wird hochgeladen…" „App läuft im Hintergrund" — deine Leiste voller Benachrichtigungen, die du nicht sehen wolltest',
    "PAIN_4": 'Diese DM, die du halb verschlafen überflogen hast — jetzt nirgendwo zu finden',
    "PAIN_OUTRO": 'NotiKeep behält sie für dich.',
    "H2_HOW": "So funktioniert es",
    "STEP1_TITLE": "Installieren und Benachrichtigungszugriff erteilen",
    "STEP1_BODY": 'Erlaube zuerst den Benachrichtigungszugriff. Die App braucht ihn, um eingehende Benachrichtigungen zu lesen.',
    "STEP2_TITLE": "Nutze dein Telefon ganz normal",
    "STEP2_IMG_ALT": "NotiKeep-Hauptansicht mit Glockensteuerung pro App",
    "STEP2_BODY": 'NotiKeep läuft im Hintergrund. Akku-Optimierung dafür zu deaktivieren wird empfohlen.',
    "STEP3_TITLE": 'Suche per Stichwort',
    "STEP3_IMG_ALT": "Eine Benachrichtigung in NotiKeep zum Archivieren wischen",
    "STEP3_BODY": 'Volltextsuche, um jede Benachrichtigung zu finden. Wichtige als Lesezeichen für schnellen Zugriff später.',
    "H2_TWO_FEATURES": "Zwei Funktionen, die NotiKeep abheben",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Bild-Zeitleiste",
    "IMT_LEAD": 'Stöbere durch die Bilder, die in Benachrichtigungen kamen — YouTube-Vorschaubilder von abonnierten Kanälen, „An diesem Tag"-Erinnerungen aus Google Photos, Fotos aus WhatsApp, Nachrichten-Vorschaubilder, Instagram-Posts. Wenn eine Benachrichtigung ein Bild enthält, wird es gespeichert.',
    "IMT_ARIA": "Schräggestelltes Telefon, aus dem Fotokarten aus dem Bild-Zeitleiste-Bildschirm fliegen",
    "IMT_CAPTION_HTML": 'Tippe ein YouTube-Vorschaubild an, um es direkt im Browser deiner Wahl abzuspielen (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">Pro-Funktion: unten</a>).',
    "YT_TITLE": "YouTube-Benachrichtigungen, dein Browser",
    "YT_LEAD": 'Tippe eine gespeicherte YouTube-Benachrichtigung an, um sie in Chrome, Firefox, Brave oder einem anderen Browser deiner Wahl abzuspielen (nur Pro).',
    "YT_IMG_ALT": "YouTube-Benachrichtigung mit Browser-Auswahldialog mit Chrome, Firefox, Brave",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "Was du bekommst",
    "F1_T": "Bild-Zeitleiste",
    "F1_P": "Durchstöbere jedes Foto, das per Benachrichtigung kam, gruppiert nach Datum.",
    "F2_T": "YouTube in jedem Browser",
    "F2_P": "Öffne YouTube-Benachrichtigungen im Browser deiner Wahl.",
    "F3_T": "Smarter Rauschfilter",
    "F3_P": "Fortschrittsbalken, Vordergrunddienste, Systempings — automatisch verworfen.",
    "F4_T": "Lesezeichen",
    "F4_P": 'Markiere wichtige mit Stern. Kein Ablaufdatum, auch in Free.',
    "F5_T": "Sicherung mit Bildern",
    "F5_P": 'Archiv plus Bilder in einem ZIP. Überlebt einen Gerätewechsel.',
    "F6_T": "Eigene Themes",
    "F6_P": 'Passe die Farbpalette der App an.',
    "F7_T": "Glockensteuerung pro App",
    "F7_P": 'Speichert Benachrichtigungen still.',
    "F8_T": "Volltextsuche",
    "F8_P": 'Finde jede Benachrichtigung am Inhalt. Free: 30 Tage, Pro: für immer.',
    "F9_T": "12 Sprachen",
    "F9_P": "Englisch, 日本語, 한국어, 中文, Español, Français, Deutsch und mehr.",
    "H2_PRICING": "Preise",
    "BEST_VALUE_LABEL": "Bestes Angebot",
    "PRICE_MONTHLY": "Monatlich",
    "PER_MO": "/Mon.",
    "PRICE_NOTE_MONTHLY": "Jederzeit kündbar",
    "PRICE_YEARLY": "Jährlich",
    "PER_YR": "/Jahr",
    "PRICE_NOTE_YEARLY": "~16 % günstiger als monatlich",
    "PRICE_LIFETIME": "Lebenslang",
    "PRICE_NOTE_LIFETIME": "Einmalig, kein Abo",
    "PRICING_DISCLAIMER": "Preise in USD. Google Play zeigt den Gegenwert in deiner Lokalwährung bei der Bezahlung.",
    "TRIAL_BANNER_HTML": 'Starte mit 7 Tagen kostenlos. Keine Abbuchung am Ende der Testphase.',
    "H3_FREE_VS_PRO": 'Free vs Pro',
    "TBL_FEATURE": "Funktion",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "Benachrichtigungsarchiv",
    "TBL_R2": "Bilder behalten (Detailansicht)",
    "TBL_R3": "Smarter Rauschfilter",
    "TBL_R4_LABEL": "Aufbewahrung",
    "TBL_R4_FREE": "30 Tage (fest)",
    "TBL_R4_PRO": "Konfigurierbar · 30 Tage → unbegrenzt",
    "TBL_R5_LABEL": "Suche",
    "TBL_R5_FREE": "Letzte 30 Tage",
    "TBL_R5_PRO": "Gesamtes Archiv",
    "TBL_R6_LABEL": "Lesezeichen · Stumm · App-Block",
    "TBL_R6_FREE": "je 5",
    "TBL_R6_PRO": "Unbegrenzt",
    "TBL_R7": "Bild-Zeitleiste (durchblätterbares Raster)",
    "TBL_R8": "YouTube in jedem Browser öffnen",
    "TBL_R9": "Sicherung mit Bildern",
    "TBL_R10_LABEL": "Eigene Themes",
    "TBL_R10_PRO": "3 Slots",
    "CTA_TRY_FREE": '7 Tage gratis testen',
    "H2_FIT": "Ist NotiKeep für dich?",
    "FIT_GREAT_TITLE": "Gut, wenn du…",
    "FIT_GREAT_1": "Schon mal eine Benachrichtigung weggewischt hast, die du brauchtest, und es sofort bereut hast",
    "FIT_GREAT_2": "Fotos, die Freunde per Messenger schicken, behalten möchtest",
    "FIT_GREAT_3": "Offline-Aufzeichnungen von WhatsApp-, Telegram-, SMS- oder Gmail-Benachrichtigungen brauchst",
    "FIT_GREAT_4": "Es leid bist, dass die YouTube-App dich bei jedem Tipp auf eine Benachrichtigung in Shorts zieht",
    "FIT_GREAT_5": "Wert darauf legst, deine Daten auf dem Gerät zu behalten, nicht in irgendeiner Cloud",
    "FIT_SKIP_TITLE": "Lieber überspringen, wenn du…",
    "FIT_SKIP_1": "Mit Androids 24-Stunden-Benachrichtigungsverlauf zufrieden bist",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "FAQ",
    "FAQ1_Q": 'Sieht NotiKeep auch Benachrichtigungen, die ich vor der Installation bekommen habe?',
    "FAQ1_A": '<strong>Nein.</strong> NotiKeep speichert nur Benachrichtigungen, die nach Installation und Erteilung des Zugriffs eintreffen.',
    "FAQ2_Q": 'Welche Android-Versionen werden unterstützt?',
    "FAQ2_A": 'Android 9.0 und neuer.',
    "FAQ3_Q": "Wie viel Speicher braucht NotiKeep?",
    "FAQ3_A": 'Textbenachrichtigungen sind winzig — wenige MB decken Monate ab. Den Platz brauchen Bilder: jedes gespeicherte Foto ist etwa 20–80 KB. Ein Vielnutzer mit 1.000 Bildbenachrichtigungen pro Monat braucht ~30–80 MB. Wenn dich der Speicher stört, verkürze die Aufbewahrungszeit.',
    "FAQ4_Q": "Was passiert mit meinen Daten bei Deinstallation?",
    "FAQ4_A": 'Alle NotiKeep-Daten — Benachrichtigungen, Bilder, Einstellungen, Lesezeichen — werden auf dem Gerät gespeichert, also löscht das Deinstallieren sie. Wenn du sie über eine Neuinstallation oder ein neues Telefon hinweg behalten willst, erwäge die Sicherung mit Bildern und Wiederherstellung (Pro-Funktion).',
    "FAQ5_Q": "Welche Berechtigungen braucht NotiKeep?",
    "FAQ5_A": 'Nur Benachrichtigungszugriff. Kein Standort, keine Kontakte, kein anderer Zugriff.',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "Kann ich meine Daten exportieren?",
    "FAQ7_A": 'Pro erstellt ein ZIP mit Datenbank, gespeicherten Bildern, Lesezeichen, Stummlisten und Einstellungen — alles in einem. Wiederherstellung auf einem neuen Telefon in einem Schritt. Den Speicherort wählst du.',
    "FAQ8_Q": "Was passiert am Ende der 7-Tage-Testphase?",
    "FAQ8_A": 'Du fällst zurück auf Free. Keine automatische Verlängerung. Wenn du Pro willst, wähle einen Plan im Upgrade-Bildschirm.',
    "FAQ9_Q": "Belastet das den Akku oder verlangsamt das Telefon?",
    "FAQ9_A": 'NotiKeep arbeitet nur, wenn eine Benachrichtigung eintrifft. Es saugt nicht an deiner Batterie.',
    "FAQ10_Q": 'Wo werden meine Daten gespeichert?',
    "FAQ10_A": 'Alle Daten bleiben auf dem Gerät. Sicherungen gehen nur zu einem Pfad, den du wählst.',
    "H2_RECENT": "Aktuelle Updates",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": 'Deine Benachrichtigungen, mit NotiKeep',
    "FINAL_CTA_P": '7 Tage gratis testen.',
    "FOOTER_MADE_BY": 'NotiKeep wird von <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a> entwickelt',
    "FOOTER_PLAY": "App auf Google Play",
    "FOOTER_PRIVACY": "Datenschutz",
    "FOOTER_SUPPORT": "Support",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# ru (Russian)
# =============================================================
"ru": {
    "F10_T": "Режим беседы",
    "F10_P": "Мессенджеры отображаются как переписки по отправителю, а фото показываются прямо в беседе.",
    "PV_HEADING": "Посмотрите в действии",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — История уведомлений',
    "META_DESCRIPTION": 'Сохраняйте уведомления вместе с фото. Открывайте уведомления YouTube в любом браузере. 7 дней бесплатно со всеми функциями. Без рекламы, все данные на устройстве.',
    "OG_TITLE": 'NotiKeep — История уведомлений',
    "OG_DESCRIPTION": 'Сохраняйте уведомления с фото. Уведомления YouTube — в любом браузере. 7 дней бесплатно. Без рекламы, данные на устройстве.',
    "HERO_H1_HTML": 'Сохранить с <span class="accent">NotiKeep</span>',
    "HERO_TAGLINE": 'Фото, коды, сообщения — храните столько, сколько хотите.',
    "HERO_IMG_ALT": "NotiKeep — главный экран с уведомлениями WhatsApp, Instagram, YouTube, Gmail и других",
    "CTA_GET": "Получить NotiKeep в Google Play",
    "TRIAL_NOTE": '',
    "H2_PAIN": 'Знакомо?',
    "PAIN_1": 'То самое фото, что друг прислал в Telegram — пропало в момент свайпа',
    "PAIN_2": '',
    "PAIN_3": '«Загрузка…» «Приложение работает в фоне» — лента, забитая уведомлениями, которые вы и видеть не хотели',
    "PAIN_4": 'Та DM, что вы пробежали полусонным — теперь её нигде не найти',
    "PAIN_OUTRO": 'NotiKeep сохранит их для вас.',
    "H2_HOW": "Как это работает",
    "STEP1_TITLE": "Установите и предоставьте Доступ к уведомлениям",
    "STEP1_BODY": 'Сначала разрешите доступ к уведомлениям. Приложению это нужно, чтобы читать поступающие уведомления.',
    "STEP2_TITLE": "Пользуйтесь телефоном как обычно",
    "STEP2_IMG_ALT": "Главный экран архива NotiKeep с управлением колокольчиком по приложениям",
    "STEP2_BODY": 'NotiKeep работает в фоне. Рекомендуется отключить оптимизацию батареи.',
    "STEP3_TITLE": 'Поиск по ключевому слову',
    "STEP3_IMG_ALT": "Свайп уведомления для архивации в NotiKeep",
    "STEP3_BODY": 'Полнотекстовый поиск находит любое уведомление. Помечайте важные в закладки для быстрого доступа.',
    "H2_TWO_FEATURES": "Две функции, выделяющие NotiKeep",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "Лента изображений",
    "IMT_LEAD": 'Просматривайте фото, пришедшие в уведомлениях — превью YouTube с подписанных каналов, воспоминания «в этот день» из Google Photos, фото из Telegram, превью новостей, посты Instagram. Если в уведомлении есть фото — оно сохранится.',
    "IMT_ARIA": "Наклонённый телефон с фото-карточками, вылетающими из экрана Ленты изображений",
    "IMT_CAPTION_HTML": 'Нажмите на превью YouTube — и видео откроется прямо в выбранном браузере (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">функция Pro: ниже</a>).',
    "YT_TITLE": "Уведомления YouTube — в вашем браузере",
    "YT_LEAD": 'Нажмите на сохранённое уведомление YouTube — оно откроется в Chrome, Firefox, Brave или любом другом браузере по вашему выбору (только Pro).',
    "YT_IMG_ALT": "Уведомление YouTube с диалогом выбора браузера: Chrome, Firefox, Brave",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "Что вы получаете",
    "F1_T": "Лента изображений",
    "F1_P": "Просматривайте каждое фото, пришедшее в уведомлении, по датам.",
    "F2_T": "YouTube в любом браузере",
    "F2_P": "Открывайте уведомления YouTube в выбранном вами браузере.",
    "F3_T": "Умный фильтр шума",
    "F3_P": "Прогресс-бары, фоновые сервисы, системные пинги — автоматически отбрасываются.",
    "F4_T": "Закладки",
    "F4_P": 'Звёздочка для важных. Без срока действия даже в Free.',
    "F5_T": "Резервная копия с изображениями",
    "F5_P": 'Архив и изображения в одном ZIP. Переживёт смену устройства.',
    "F6_T": "Свои темы",
    "F6_P": 'Настройте цветовую палитру приложения.',
    "F7_T": "Колокольчик по приложению",
    "F7_P": 'Уведомления сохраняются беззвучно.',
    "F8_T": "Полнотекстовый поиск",
    "F8_P": 'Найдите любое уведомление по содержимому. Free: 30 дней, Pro: навсегда.',
    "F9_T": "12 языков",
    "F9_P": "Английский, 日本語, 한국어, 中文, Español, Français, Deutsch и другие.",
    "H2_PRICING": "Цены",
    "BEST_VALUE_LABEL": "Выгоднее всего",
    "PRICE_MONTHLY": "Месяц",
    "PER_MO": "/мес",
    "PRICE_NOTE_MONTHLY": "Отмена в любой момент",
    "PRICE_YEARLY": "Год",
    "PER_YR": "/год",
    "PRICE_NOTE_YEARLY": "На ~16 % дешевле помесячного",
    "PRICE_LIFETIME": "Навсегда",
    "PRICE_NOTE_LIFETIME": "Разовая оплата, без подписки",
    "PRICING_DISCLAIMER": "Цены указаны в USD. Google Play отображает эквивалент в вашей локальной валюте при оплате.",
    "TRIAL_BANNER_HTML": 'Начните с 7 дней бесплатно. По окончании пробного периода списаний нет.',
    "H3_FREE_VS_PRO": 'Free vs Pro',
    "TBL_FEATURE": "Функция",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "Архив уведомлений",
    "TBL_R2": "Сохранение изображений (детальный вид)",
    "TBL_R3": "Умный фильтр шума",
    "TBL_R4_LABEL": "Срок хранения",
    "TBL_R4_FREE": "30 дней (фикс.)",
    "TBL_R4_PRO": "Настраиваемо · 30 дней → без ограничений",
    "TBL_R5_LABEL": "Поиск",
    "TBL_R5_FREE": "Последние 30 дней",
    "TBL_R5_PRO": "Весь архив",
    "TBL_R6_LABEL": "Закладки · Беззвучно · Блок",
    "TBL_R6_FREE": "По 5",
    "TBL_R6_PRO": "Без ограничений",
    "TBL_R7": "Лента изображений (просмотр сеткой)",
    "TBL_R8": "Открывать YouTube в любом браузере",
    "TBL_R9": "Копия с изображениями",
    "TBL_R10_LABEL": "Свои темы",
    "TBL_R10_PRO": "3 слота",
    "CTA_TRY_FREE": 'Попробовать 7 дней бесплатно',
    "H2_FIT": "Подходит ли вам NotiKeep?",
    "FIT_GREAT_TITLE": "Подходит, если вы…",
    "FIT_GREAT_1": "Когда-нибудь смахивали нужное уведомление и тут же жалели",
    "FIT_GREAT_2": "Хотите сохранять фото, что друзья присылают в мессенджерах",
    "FIT_GREAT_3": "Нуждаетесь в офлайн-записях уведомлений Telegram, WhatsApp, SMS или Gmail",
    "FIT_GREAT_4": "Устали от того, что приложение YouTube затягивает в Shorts при каждом тапе по уведомлению",
    "FIT_GREAT_5": "Заботитесь о том, чтобы данные оставались на устройстве, а не в чьём-то облаке",
    "FIT_SKIP_TITLE": "Можно пропустить, если вы…",
    "FIT_SKIP_1": "Довольны встроенной 24-часовой историей уведомлений Android",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "Часто задаваемые вопросы",
    "FAQ1_Q": 'Видит ли NotiKeep уведомления, полученные до его установки?',
    "FAQ1_A": '<strong>Нет.</strong> NotiKeep сохраняет только уведомления, пришедшие после установки и предоставления доступа к уведомлениям.',
    "FAQ2_Q": 'Какие версии Android поддерживаются?',
    "FAQ2_A": 'Android 9.0 и новее.',
    "FAQ3_Q": "Сколько места занимает NotiKeep?",
    "FAQ3_A": 'Текстовые уведомления крошечные — нескольких МБ хватает на месяцы. Место занимают изображения: каждое сохранённое фото около 20–80 КБ. Активный пользователь с 1 000 уведомлений с фото в месяц использует ~30–80 МБ. Если беспокоит — сократите срок хранения.',
    "FAQ4_Q": "Что станет с моими данными при удалении?",
    "FAQ4_A": 'Все данные NotiKeep — уведомления, изображения, настройки, закладки — хранятся на устройстве, поэтому удаление приложения их стирает. Чтобы сохранить архив при переустановке или новом устройстве, заранее воспользуйтесь резервной копией с изображениями и восстановлением (функция Pro).',
    "FAQ5_Q": "Какие разрешения нужны NotiKeep?",
    "FAQ5_A": 'Только доступ к уведомлениям. Без геолокации, без контактов, без других доступов.',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "Можно ли экспортировать данные?",
    "FAQ7_A": 'Pro создаёт ZIP с базой данных, сохранёнными изображениями, закладками, списками беззвучных и настройками — всё вместе. Восстановление на новом устройстве в один шаг. Место сохранения вы выбираете сами.',
    "FAQ8_Q": "Что происходит в конце 7-дневного пробного периода?",
    "FAQ8_A": 'Возвращаетесь на Free. Без автопродления. Если хотите Pro — выберите план в окне обновления.',
    "FAQ9_Q": "Сажает ли это батарею или замедляет телефон?",
    "FAQ9_A": 'NotiKeep работает только в момент прихода уведомления. Не сидит и не разряжает батарею.',
    "FAQ10_Q": 'Где хранятся мои данные?',
    "FAQ10_A": 'Все данные остаются на устройстве. Резервные копии идут только по выбранному вами пути.',
    "H2_RECENT": "Последние обновления",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": 'Ваши уведомления — с NotiKeep',
    "FINAL_CTA_P": 'Попробуйте 7 дней бесплатно.',
    "FOOTER_MADE_BY": 'NotiKeep сделан <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a>',
    "FOOTER_PLAY": "Приложение в Google Play",
    "FOOTER_PRIVACY": "Политика конфиденциальности",
    "FOOTER_SUPPORT": "Поддержка",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# ar (Arabic)
# =============================================================
"ar": {
    "F10_T": "عرض المحادثة",
    "F10_P": "تظهر تطبيقات المراسلة كمحادثات مجمّعة حسب المُرسِل، مع عرض الصور داخل المحادثة.",
    "PV_HEADING": "شاهده أثناء العمل",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — سجل الإشعارات',
    "META_DESCRIPTION": 'احفظ إشعاراتك بما فيها الصور. افتح إشعارات YouTube في أي متصفح. 7 أيام مجانًا بكل الميزات. بلا إعلانات، كل البيانات على الجهاز.',
    "OG_TITLE": 'NotiKeep — سجل الإشعارات',
    "OG_DESCRIPTION": 'احفظ إشعاراتك بالصور. افتح إشعارات YouTube في أي متصفح. تجربة مجانية 7 أيام. بلا إعلانات، البيانات على الجهاز.',
    "HERO_H1_HTML": 'احفظ مع <span class="accent">NotiKeep</span>',
    "HERO_TAGLINE": 'الصور والرموز والرسائل — محفوظة طوال المدة التي تريدها.',
    "HERO_IMG_ALT": "NotiKeep — الشاشة الرئيسية تعرض إشعارات WhatsApp وInstagram وYouTube وGmail والمزيد",
    "CTA_GET": "احصل على NotiKeep من Google Play",
    "TRIAL_NOTE": '',
    "H2_PAIN": 'هل مرّ بك هذا؟',
    "PAIN_1": 'تلك الصورة التي أرسلها صديق في WhatsApp — اختفت لحظة سحبتك',
    "PAIN_2": '',
    "PAIN_3": '«جارٍ الرفع…» «التطبيق يعمل في الخلفية» — شريطك مكدّس بإشعارات لم ترغب في رؤيتها',
    "PAIN_4": 'تلك الرسالة الخاصة التي مررت عليها وأنت نصف نائم — لا تجدها الآن في أي مكان',
    "PAIN_OUTRO": 'يحتفظ بها لك NotiKeep.',
    "H2_HOW": "آلية العمل",
    "STEP1_TITLE": "ثبّت ومنح صلاحية الوصول إلى الإشعارات",
    "STEP1_BODY": 'أولًا، اسمح بالوصول إلى الإشعارات. التطبيق يحتاج إلى ذلك لقراءة الإشعارات الواردة.',
    "STEP2_TITLE": "استخدم هاتفك بشكل طبيعي",
    "STEP2_IMG_ALT": "العرض الرئيسي لأرشيف NotiKeep مع التحكم بالجرس لكل تطبيق",
    "STEP2_BODY": 'يعمل NotiKeep في الخلفية. يُنصح بإيقاف تحسين البطارية.',
    "STEP3_TITLE": 'ابحث بكلمة مفتاحية',
    "STEP3_IMG_ALT": "سحب إشعار لأرشفته في NotiKeep",
    "STEP3_BODY": 'بحث في النص الكامل للعثور على أي إشعار. أضف المهم إلى المفضلة للوصول السريع لاحقًا.',
    "H2_TWO_FEATURES": "ميزتان تُميّزان NotiKeep",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "الصور في سطر زمني",
    "IMT_LEAD": 'تصفح الصور التي وصلت في الإشعارات — صور مصغّرة من قنوات YouTube التي تتابعها، ذكريات «في مثل هذا اليوم» من Google Photos، صور من WhatsApp، صور أخبار، منشورات Instagram. إن تضمّن الإشعار صورة فهي محفوظة.',
    "IMT_ARIA": "هاتف مائل جانبيًا تتطاير منه بطاقات صور من شاشة الصور في سطر زمني",
    "IMT_CAPTION_HTML": 'انقر على صورة YouTube مصغّرة لتشغيلها مباشرة في المتصفح الذي تختاره (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">ميزة Pro: في الأسفل</a>).',
    "YT_TITLE": "إشعارات YouTube، في متصفحك",
    "YT_LEAD": 'انقر على إشعار YouTube محفوظ لتشغيله في Chrome أو Firefox أو Brave أو أي متصفح آخر تختاره (Pro فقط).',
    "YT_IMG_ALT": "إشعار YouTube مع مربّع حوار اختيار المتصفح يعرض Chrome وFirefox وBrave",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "ما تحصل عليه",
    "F1_T": "الصور في سطر زمني",
    "F1_P": "تصفّح كل صورة وصلت ضمن إشعار، مرتّبة حسب التاريخ.",
    "F2_T": "YouTube في أي متصفح",
    "F2_P": "افتح إشعارات YouTube في المتصفح الذي تختاره.",
    "F3_T": "فلتر ضوضاء ذكي",
    "F3_P": "أشرطة التقدم وخدمات الواجهة وإشعارات النظام — تُسقط تلقائيًا.",
    "F4_T": "المفضّلة",
    "F4_P": 'ضع نجمة على المهمة. لا تنتهي صلاحيتها حتى في Free.',
    "F5_T": "نسخة احتياطية",
    "F5_P": 'الأرشيف والصور في ملف ZIP واحد. ينجو من تغيير الجهاز.',
    "F6_T": "ثيمات مخصّصة",
    "F6_P": 'خصّص ألوان واجهة التطبيق.',
    "F7_T": "تحكّم بالجرس لكل تطبيق",
    "F7_P": 'تُحفظ الإشعارات بصمت.',
    "F8_T": "بحث نص كامل",
    "F8_P": 'اعثر على أي إشعار بمحتواه. Free: 30 يومًا، Pro: للأبد.',
    "F9_T": "12 لغة",
    "F9_P": "الإنجليزية، 日本語، 한국어، 中文، Español، Français، Deutsch وغيرها.",
    "H2_PRICING": "الأسعار",
    "BEST_VALUE_LABEL": "الأفضل قيمة",
    "PRICE_MONTHLY": "شهري",
    "PER_MO": "/شهر",
    "PRICE_NOTE_MONTHLY": "إلغاء في أي وقت",
    "PRICE_YEARLY": "سنوي",
    "PER_YR": "/سنة",
    "PRICE_NOTE_YEARLY": "أرخص بنحو 16% من الشهري",
    "PRICE_LIFETIME": "مدى الحياة",
    "PRICE_NOTE_LIFETIME": "دفعة واحدة، بلا اشتراك",
    "PRICING_DISCLAIMER": "الأسعار المعروضة بالدولار الأمريكي. يعرض Google Play المعادل بعملتك المحلية عند الدفع.",
    "TRIAL_BANNER_HTML": 'ابدأ بـ7 أيام مجانية. لا فاتورة عند انتهاء التجربة.',
    "H3_FREE_VS_PRO": 'Free مقابل Pro',
    "TBL_FEATURE": "الميزة",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "أرشيف الإشعارات",
    "TBL_R2": "حفظ الصور (في عرض التفاصيل)",
    "TBL_R3": "فلتر ضوضاء ذكي",
    "TBL_R4_LABEL": "مدة الحفظ",
    "TBL_R4_FREE": "30 يومًا (ثابت)",
    "TBL_R4_PRO": "قابل للضبط · 30 يومًا → غير محدود",
    "TBL_R5_LABEL": "البحث",
    "TBL_R5_FREE": "آخر 30 يومًا",
    "TBL_R5_PRO": "كامل الأرشيف",
    "TBL_R6_LABEL": "المفضّلة · الكتم · حظر التطبيقات",
    "TBL_R6_FREE": "5 لكل منها",
    "TBL_R6_PRO": "غير محدود",
    "TBL_R7": "الصور في سطر زمني (شبكة قابلة للتصفح)",
    "TBL_R8": "فتح YouTube في أي متصفح",
    "TBL_R9": "نسخة احتياطية بالصور",
    "TBL_R10_LABEL": "ثيمات مخصّصة",
    "TBL_R10_PRO": "3 خانات",
    "CTA_TRY_FREE": 'جرّب 7 أيام مجانًا',
    "H2_FIT": "هل NotiKeep يناسبك؟",
    "FIT_GREAT_TITLE": "مناسب جدًا إذا كنت…",
    "FIT_GREAT_1": "سحبت يومًا إشعارًا تحتاجه ثم ندمت فورًا",
    "FIT_GREAT_2": "تريد الاحتفاظ بالصور التي يرسلها الأصدقاء عبر تطبيقات المراسلة",
    "FIT_GREAT_3": "تحتاج سجلات بلا اتصال لإشعارات WhatsApp وTelegram وSMS أو Gmail",
    "FIT_GREAT_4": "سئمت من أن يجرّك تطبيق YouTube إلى Shorts كل مرة تنقر فيها على إشعار",
    "FIT_GREAT_5": "تهتم ببقاء بياناتك على الجهاز لا في سحابة شخص آخر",
    "FIT_SKIP_TITLE": "تجاوز إذا كنت…",
    "FIT_SKIP_1": "راضيًا عن سجل إشعارات Android المدمج لمدة 24 ساعة",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "الأسئلة الشائعة",
    "FAQ1_Q": 'هل يستطيع NotiKeep رؤية إشعارات وصلت قبل تثبيته؟',
    "FAQ1_A": '<strong>لا.</strong> لا يحفظ NotiKeep إلا الإشعارات التي تصل بعد التثبيت ومنح الوصول إلى الإشعارات.',
    "FAQ2_Q": 'ما إصدارات Android المدعومة؟',
    "FAQ2_A": 'Android 9.0 فما فوق.',
    "FAQ3_Q": "كم من المساحة يستخدم NotiKeep؟",
    "FAQ3_A": 'إشعارات النص صغيرة جدًا — بضعة ميغابايت تغطي أشهرًا. ما يستهلك المساحة هو الصور: كل صورة محفوظة نحو 20–80 كيلوبايت. مستخدم كثيف بألف إشعار بصور شهريًا يستخدم ~30–80 ميغابايت. إن قلقت من المساحة، قصّر مدة الحفظ.',
    "FAQ4_Q": "ماذا يحدث لبياناتي إذا أزلت التطبيق؟",
    "FAQ4_A": 'جميع بيانات NotiKeep — الإشعارات والصور والتفضيلات والمفضلة — تُخزَّن على الجهاز، لذا إلغاء التثبيت يحذفها. للاحتفاظ بها بعد إعادة التثبيت أو هاتف جديد، ضع في اعتبارك النسخ الاحتياطي مع الصور والاستعادة (ميزة Pro).',
    "FAQ5_Q": "ما الصلاحيات التي يحتاجها NotiKeep؟",
    "FAQ5_A": 'الوصول إلى الإشعارات فقط. لا موقع، لا جهات اتصال، لا وصول آخر.',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "هل يمكنني تصدير بياناتي؟",
    "FAQ7_A": 'ينشئ Pro ملف ZIP يضم قاعدة البيانات والصور المحفوظة والمفضلة وقوائم الكتم والإعدادات — كله معًا. الاستعادة على هاتف جديد بخطوة واحدة. مكان الحفظ تختاره أنت.',
    "FAQ8_Q": "ماذا يحدث في نهاية تجربة الـ7 أيام؟",
    "FAQ8_A": 'تعود إلى Free. بلا تجديد تلقائي. إن أردت Pro، اختر خطة من شاشة الترقية.',
    "FAQ9_Q": "هل يستهلك البطارية أو يبطئ الهاتف؟",
    "FAQ9_A": 'يعمل NotiKeep فقط لحظة وصول إشعار. لا يجلس مستهلكًا للبطارية.',
    "FAQ10_Q": 'أين تُخزَّن بياناتي؟',
    "FAQ10_A": 'تبقى كل البيانات على الجهاز. والنسخ الاحتياطية تذهب فقط إلى مسار تختاره أنت.',
    "H2_RECENT": "آخر التحديثات",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": 'إشعاراتك مع NotiKeep',
    "FINAL_CTA_P": 'جرّب 7 أيام مجانًا.',
    "FOOTER_MADE_BY": 'NotiKeep من تطوير <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a>',
    "FOOTER_PLAY": "التطبيق على Google Play",
    "FOOTER_PRIVACY": "سياسة الخصوصية",
    "FOOTER_SUPPORT": "الدعم",
    "FOOTER_DISCLOSURE": '',
},

# =============================================================
# hi (Hindi)
# =============================================================
"hi": {
    "F10_T": "बातचीत व्यू",
    "F10_P": "मैसेजिंग ऐप्स भेजने वाले के अनुसार चैट के रूप में दिखती हैं, फ़ोटो बातचीत के अंदर ही।",
    "PV_HEADING": "इसे काम करते देखें",
    "PV_VIDEO_ID": "YmGIVUZAdXI",
    "TITLE": 'NotiKeep — सूचना इतिहास',
    "META_DESCRIPTION": 'तस्वीरों सहित सूचनाएँ सहेजें। YouTube सूचनाएँ किसी भी ब्राउज़र में खोलें। 7 दिन सभी सुविधाओं के साथ मुफ़्त। कोई विज्ञापन नहीं, सारा डेटा डिवाइस पर।',
    "OG_TITLE": 'NotiKeep — सूचना इतिहास',
    "OG_DESCRIPTION": 'तस्वीरों सहित सूचनाएँ सहेजें। YouTube सूचनाएँ किसी भी ब्राउज़र में। 7 दिन मुफ़्त। कोई विज्ञापन नहीं, डेटा डिवाइस पर।',
    "HERO_H1_HTML": '<span class="accent">NotiKeep</span> के साथ सहेजें',
    "HERO_TAGLINE": 'तस्वीरें, कोड, संदेश — जब तक चाहें सहेजे रखें।',
    "HERO_IMG_ALT": "NotiKeep — मुख्य स्क्रीन WhatsApp, Instagram, YouTube, Gmail और अन्य के नोटिफ़िकेशन दिखा रही",
    "CTA_GET": "Google Play पर NotiKeep पाएं",
    "TRIAL_NOTE": '',
    "H2_PAIN": 'क्या आपके साथ भी होता है?',
    "PAIN_1": 'वो तस्वीर जो दोस्त ने अभी WhatsApp पर भेजी थी — स्वाइप करते ही ग़ायब',
    "PAIN_2": '',
    "PAIN_3": '«अपलोड हो रहा है…» «ऐप पृष्ठभूमि में चल रहा है» — आपकी ट्रे ऐसी सूचनाओं से भरी जो आप देखना भी नहीं चाहते थे',
    "PAIN_4": 'वो DM जिसे आप आधी नींद में देख गए थे — अब कहीं नहीं मिल रहा',
    "PAIN_OUTRO": 'NotiKeep इन्हें सहेज लेगा।',
    "H2_HOW": "कैसे काम करता है",
    "STEP1_TITLE": "इंस्टॉल करें और नोटिफ़िकेशन एक्सेस दें",
    "STEP1_BODY": 'पहले, सूचना एक्सेस की अनुमति दें। ऐप को आती हुई सूचनाएँ पढ़ने के लिए यह चाहिए।',
    "STEP2_TITLE": "फ़ोन सामान्य रूप से इस्तेमाल करें",
    "STEP2_IMG_ALT": "NotiKeep मुख्य आर्काइव दृश्य ऐप-वार बेल नियंत्रण के साथ",
    "STEP2_BODY": 'NotiKeep पृष्ठभूमि में चलता है। बैटरी ऑप्टिमाइज़ेशन को बंद करना अनुशंसित है।',
    "STEP3_TITLE": 'कीवर्ड से खोजें',
    "STEP3_IMG_ALT": "NotiKeep में नोटिफ़िकेशन को आर्काइव करने के लिए स्वाइप करना",
    "STEP3_BODY": 'किसी भी सूचना को पूर्ण-पाठ खोज से ढूँढें। ज़रूरी को बुकमार्क कर लें ताकि बाद में जल्दी मिलें।',
    "H2_TWO_FEATURES": "NotiKeep को अलग करने वाली दो विशेषताएँ",
    "ONLY_BADGE": "Only in NotiKeep",
    "IMT_TITLE": "इमेज टाइमलाइन",
    "IMT_LEAD": 'सूचनाओं में आई तस्वीरों को एक साथ देखें — फ़ॉलो किए चैनलों के YouTube थंबनेल, Google Photos के «कई साल पहले आज», WhatsApp पर मिली तस्वीरें, समाचार थंबनेल, Instagram पोस्ट। अगर सूचना में तस्वीर है, तो वह सहेज ली जाती है।',
    "IMT_ARIA": "इमेज टाइमलाइन स्क्रीन से उड़ते फ़ोटो कार्ड्स के साथ बगल में झुका फ़ोन",
    "IMT_CAPTION_HTML": 'YouTube थंबनेल पर टैप करें, और वह सीधे आपकी पसंद के ब्राउज़र में चलने लगेगी (<a href="#browser-choice" style="color:inherit;text-decoration:underline;">Pro सुविधा: नीचे</a>)।',
    "YT_TITLE": "YouTube नोटिफ़िकेशन, आपके ब्राउज़र में",
    "YT_LEAD": 'सहेजी गई YouTube सूचना पर टैप करें और उसे Chrome, Firefox, Brave या किसी भी पसंदीदा ब्राउज़र में चलाएँ (केवल Pro में)।',
    "YT_IMG_ALT": "YouTube नोटिफ़िकेशन के साथ ब्राउज़र-चयन डायलॉग जिसमें Chrome, Firefox, Brave",
    "YT_CAPTION": '',
    "H2_WHAT_YOU_GET": "आपको क्या मिलता है",
    "F1_T": "इमेज टाइमलाइन",
    "F1_P": "नोटिफ़िकेशन में आई हर तस्वीर को तारीख़ के अनुसार ब्राउज़ करें।",
    "F2_T": "किसी भी ब्राउज़र में YouTube",
    "F2_P": "अपनी पसंद के ब्राउज़र में YouTube नोटिफ़िकेशन खोलें।",
    "F3_T": "स्मार्ट शोर फ़िल्टर",
    "F3_P": "प्रगति बार, अग्रभूमि सेवाएँ, सिस्टम पिंग — स्वतः छोड़ दिए जाते हैं।",
    "F4_T": "बुकमार्क",
    "F4_P": 'ज़रूरी को स्टार करें। Free में भी समाप्त नहीं होते।',
    "F5_T": "छवियों सहित बैकअप",
    "F5_P": 'आर्काइव और तस्वीरें एक ZIP में। डिवाइस बदलने पर भी बने रहें।',
    "F6_T": "कस्टम थीम",
    "F6_P": 'ऐप के रंगों को कस्टमाइज़ करें।',
    "F7_T": "ऐप-वार बेल नियंत्रण",
    "F7_P": 'सूचनाएँ चुपचाप सहेजी जाती हैं।',
    "F8_T": "पूर्ण-पाठ खोज",
    "F8_P": 'किसी भी सूचना को सामग्री से खोजें। Free: 30 दिन, Pro: हमेशा।',
    "F9_T": "12 भाषाएँ",
    "F9_P": "अंग्रेज़ी, 日本語, 한국어, 中文, Español, Français, Deutsch और अधिक।",
    "H2_PRICING": "मूल्य",
    "BEST_VALUE_LABEL": "सबसे फ़ायदेमंद",
    "PRICE_MONTHLY": "मासिक",
    "PER_MO": "/माह",
    "PRICE_NOTE_MONTHLY": "कभी भी रद्द",
    "PRICE_YEARLY": "वार्षिक",
    "PER_YR": "/वर्ष",
    "PRICE_NOTE_YEARLY": "मासिक से ~16% सस्ता",
    "PRICE_LIFETIME": "आजीवन",
    "PRICE_NOTE_LIFETIME": "एकमुश्त, कोई सदस्यता नहीं",
    "PRICING_DISCLAIMER": "दिखाई गई कीमतें USD में हैं। Google Play चेकआउट के समय आपकी स्थानीय मुद्रा में समतुल्य राशि दिखाता है।",
    "TRIAL_BANNER_HTML": '7 दिन का मुफ़्त ट्रायल से शुरुआत। ट्रायल के अंत में कोई शुल्क नहीं।',
    "H3_FREE_VS_PRO": 'Free बनाम Pro',
    "TBL_FEATURE": "सुविधा",
    "TBL_FREE": "Free",
    "TBL_PRO": "Pro",
    "TBL_R1": "नोटिफ़िकेशन आर्काइव",
    "TBL_R2": "छवि सुरक्षित (विवरण दृश्य में)",
    "TBL_R3": "स्मार्ट शोर फ़िल्टर",
    "TBL_R4_LABEL": "संग्रहण",
    "TBL_R4_FREE": "30 दिन (निश्चित)",
    "TBL_R4_PRO": "विन्यास योग्य · 30 दिन → असीमित",
    "TBL_R5_LABEL": "खोज",
    "TBL_R5_FREE": "पिछले 30 दिन",
    "TBL_R5_PRO": "पूरा आर्काइव",
    "TBL_R6_LABEL": "बुकमार्क · म्यूट · ऐप ब्लॉक",
    "TBL_R6_FREE": "5 प्रत्येक",
    "TBL_R6_PRO": "असीमित",
    "TBL_R7": "इमेज टाइमलाइन (ब्राउज़ करने योग्य ग्रिड)",
    "TBL_R8": "किसी भी ब्राउज़र में YouTube खोलें",
    "TBL_R9": "छवियों सहित बैकअप",
    "TBL_R10_LABEL": "कस्टम थीम",
    "TBL_R10_PRO": "3 स्लॉट",
    "CTA_TRY_FREE": '7 दिन मुफ़्त आज़माएँ',
    "H2_FIT": "क्या NotiKeep आपके लिए है?",
    "FIT_GREAT_TITLE": "बढ़िया मेल अगर आप…",
    "FIT_GREAT_1": "ज़रूरी नोटिफ़िकेशन को कभी ग़लती से स्वाइप करके तुरंत पछताए हैं",
    "FIT_GREAT_2": "मेसेजिंग ऐप्स पर दोस्तों की भेजी तस्वीरों को रखना चाहते हैं",
    "FIT_GREAT_3": "WhatsApp, Telegram, SMS या Gmail नोटिफ़िकेशन का ऑफ़लाइन रिकॉर्ड चाहते हैं",
    "FIT_GREAT_4": "हर बार नोटिफ़िकेशन टैप करते ही YouTube ऐप के Shorts में खींचे जाने से थक चुके हैं",
    "FIT_GREAT_5": "अपना डेटा किसी की क्लाउड में नहीं, अपने डिवाइस पर रखना चाहते हैं",
    "FIT_SKIP_TITLE": "छोड़ दें अगर आप…",
    "FIT_SKIP_1": "Android के बिल्ट-इन 24 घंटे के नोटिफ़िकेशन इतिहास से संतुष्ट हैं",
    "FIT_SKIP_2": '',
    "FIT_SKIP_3": '',
    "FIT_SKIP_4": '',
    "H2_FAQ": "FAQ",
    "FAQ1_Q": 'क्या NotiKeep इंस्टॉल करने से पहले की सूचनाएँ देख सकता है?',
    "FAQ1_A": '<strong>नहीं।</strong> NotiKeep सिर्फ़ वही सूचनाएँ सहेजता है जो इंस्टॉल और सूचना एक्सेस मिलने के बाद आती हैं।',
    "FAQ2_Q": 'कौन से Android संस्करण समर्थित हैं?',
    "FAQ2_A": 'Android 9.0 और बाद के।',
    "FAQ3_Q": "NotiKeep कितनी जगह लेता है?",
    "FAQ3_A": 'टेक्स्ट सूचनाएँ बहुत छोटी होती हैं — कुछ MB महीनों के लिए काफ़ी। जगह तस्वीरों से जाती है: हर सहेजी तस्वीर लगभग 20–80 KB। महीने में 1,000 छवि-सहित सूचनाओं वाला भारी उपयोगकर्ता ~30–80 MB इस्तेमाल करता है। चिंता हो तो रिटेंशन अवधि घटाएँ।',
    "FAQ4_Q": "अनइंस्टॉल करने पर मेरे डेटा का क्या होता है?",
    "FAQ4_A": 'NotiKeep का सारा डेटा — सूचनाएँ, तस्वीरें, प्राथमिकताएँ, बुकमार्क — डिवाइस पर रहता है, इसलिए अनइंस्टॉल करने पर मिट जाता है। पुनः-इंस्टॉल या नए फ़ोन पर बचाए रखने के लिए, छवि सहित बैकअप और रिस्टोर (Pro सुविधा) पर विचार करें।',
    "FAQ5_Q": "NotiKeep को कौन-सी अनुमतियाँ चाहिए?",
    "FAQ5_A": 'केवल सूचना एक्सेस। न स्थान, न संपर्क, न कोई और एक्सेस।',
    "FAQ6_Q": '',
    "FAQ6_A": '',
    "FAQ7_Q": "क्या मैं अपना डेटा निर्यात कर सकता हूँ?",
    "FAQ7_A": 'Pro एक ZIP बनाता है जिसमें डेटाबेस, सहेजी गई तस्वीरें, बुकमार्क, म्यूट सूचियाँ, और सेटिंग्स — सब एक साथ। नए फ़ोन में एक चरण में पुनर्स्थापित। सहेजने का स्थान आप चुनते हैं।',
    "FAQ8_Q": "7 दिन के ट्रायल के अंत में क्या होता है?",
    "FAQ8_A": 'Free पर लौट जाते हैं। कोई स्वतः नवीनीकरण नहीं। Pro चाहिए तो अपग्रेड स्क्रीन से कोई योजना चुनें।',
    "FAQ9_Q": "क्या इससे बैटरी या फ़ोन धीमा होगा?",
    "FAQ9_A": 'NotiKeep केवल तभी काम करता है जब कोई सूचना आती है। बैटरी सोखता हुआ नहीं बैठा रहता।',
    "FAQ10_Q": 'मेरा डेटा कहाँ संग्रहीत होता है?',
    "FAQ10_A": 'सारा डेटा डिवाइस पर ही रहता है। बैकअप भी सिर्फ़ आपके चुने हुए पथ पर जाते हैं।',
    "H2_RECENT": "हाल के अपडेट",
    "CL_127": '',
    "CL_126": '',
    "CL_125": '',
    "CL_124": '',
    "CL_123": '',
    "EARLIER_LABEL": '',
    "EARLY_1": '',
    "EARLY_2": '',
    "EARLY_3": '',
    "EARLY_4": '',
    "EARLY_5": '',
    "FINAL_CTA_H2": 'आपकी सूचनाएँ, NotiKeep के साथ',
    "FINAL_CTA_P": '7 दिन मुफ़्त आज़माएँ।',
    "FOOTER_MADE_BY": 'NotiKeep को <a href="https://sakura.dev.jp" style="color:inherit">sakura.dev.jp</a> ने बनाया है',
    "FOOTER_PLAY": "Google Play पर ऐप",
    "FOOTER_PRIVACY": "गोपनीयता नीति",
    "FOOTER_SUPPORT": "सहायता",
    "FOOTER_DISCLOSURE": '',
},

}
